const namespaced = true

const state = {
  commandersList: [
    {name: "Aboshan, Cephalid Emperor",colors: ['u']},
    {name: "Adamaro, First to Desire",colors: ['r']},
    {name: "Adriana, Captain of the Guard",colors: ['r', 'w']},
    {name: "Adun Oakenshield",colors: ['b', 'r', 'g']},
    {name: "Agrus Kos, Wojek Veteran",colors: ['r', 'w']},
    {name: "Akiri, Line-Slinger",colors: ['r', 'w']},
    {name: "Akroma, Angel of Fury",colors: ['r']},
    {name: "Akroma, Angel of Wrath",colors: ['w']},
    {name: "Akuta, Born of Ash",colors: ['b']},
    {name: "Alesha, Who Smiles at Death",colors: ['r', 'w', 'b']},
    {name: "Alexi, Zephyr Mage",colors: ['u']},
    {name: "Alhammarret, High Arbiter",colors: ['u']},
    {name: "Ambassador Laquatus",colors: ['u']},
    {name: "Anafenza, Kin-Tree Spirit",colors: ['w']},
    {name: "Anafenza, the Foremost",colors: ['w', 'b', 'g']},
    {name: "Anax and Cymede",colors: ['r', 'w']},
    {name: "Angus Mackenzie",colors: ['g', 'w', 'u']},
    {name: "Animar, Soul of Elements",colors: ['g', 'u', 'r']},
    {name: "Anowon, the Ruin Sage",colors: ['b']},
    {name: "Anthousa, Setessan Hero",colors: ['g']},
    {name: "Anya, Merciless Angel",colors: ['r', 'w']},
    {name: "Arahbo, Roar of the World",colors: ['g', 'w']},
    {name: "Arashi, the Sky Asunder",colors: ['g']},
    {name: "Arcades Sabboth",colors: ['g', 'w', 'u']},
    {name: "Arcanis the Omnipotent",colors: ['u']},
    {name: "Archangel Avacyn",colors: ['r', 'w']},
    {name: "Arcum Dagsson",colors: ['u']},
    {name: "Arjun, the Shifting Flame",colors: ['u', 'r']},
    {name: "Ascendant Evincar",colors: ['b']},
    {name: "Ashling, the Extinguisher",colors: ['b']},
    {name: "Ashling the Pilgrim",colors: ['r']},
    {name: "Asmira, Holy Avenger",colors: ['g', 'w']},
    {name: "Atalya, Samite Master",colors: ['w']},
    {name: "Atarka, World Render",colors: ['r', 'g']},
    {name: "Athreos, God of Passage",colors: ['w', 'b']},
    {name: "Atogatog",colors: ['w', 'u', 'b', 'r', 'g']},
    {name: "Atraxa, Praetors' Voice",colors: ['g', 'w', 'u', 'b']},
    {name: "Aurelia, the Warleader",colors: ['r', 'w']},
    {name: "Autumn Willow",colors: ['g']},
    {name: "Avacyn, Angel of Hope",colors: ['w']},
    {name: "Avacyn, Guardian Angel",colors: ['w']},
    {name: "Avacyn, the Purifier",colors: ['r', 'w']},
    {name: "Axelrod Gunnarson",colors: ['b', 'r']},
    {name: "Ayesha Tanaka",colors: ['w', 'u']},
    {name: "Ayli, Eternal Pilgrim",colors: ['w', 'b']},
    {name: "Ayumi, the Last Visitor",colors: ['g']},
    {name: "Azami, Lady of Scrolls",colors: ['u']},
    {name: "Azusa, Lost but Seeking",colors: ['g']},
    {name: "Balan, Wandering Knight",colors: ['w']},
    {name: "Balthor the Defiled",colors: ['b']},
    {name: "Balthor the Stout",colors: ['r']},
    {name: "Baral, Chief of Compliance",colors: ['u']},
    {name: "Barktooth Warbeard",colors: ['b', 'r']},
    {name: "Baron Sengir",colors: ['b']},
    {name: "Barrin, Master Wizard",colors: ['u']},
    {name: "Bartel Runeaxe",colors: ['b', 'r', 'g']},
    {name: "Baru, Fist of Krosa",colors: ['g']},
    {name: "Basandra, Battle Seraph",colors: ['r', 'w']},
    {name: "Ben-Ben, Akki Hermit",colors: ['r']},
    {name: "Bladewing the Risen",colors: ['b', 'r']},
    {name: "Blind Seer",colors: ['u']},
    {name: "Bontu the Glorified",colors: ['b']},
    {name: "Borborygmos",colors: ['r', 'g']},
    {name: "Borborygmos Enraged",colors: ['r', 'g']},
    {name: "Boris Devilboon",colors: ['b', 'r']},
    {name: "Bosh, Iron Golem",colors: ['r']},
    {name: "Bounteous Kirin",colors: ['g']},
    {name: "Brago, King Eternal",colors: ['w', 'u']},
    {name: "Braids, Conjurer Adept",colors: ['u']},
    {name: "Breya, Etherium Shaper",colors: ['w', 'u', 'b', 'r']},
    {name: "Brigid, Hero of Kinsbaile",colors: ['w']},
    {name: "Brimaz, King of Oreskos",colors: ['w']},
    {name: "Brion Stoutarm",colors: ['r', 'w']},
    {name: "Brothers Yamazaki",colors: ['r']},
    {name: "Bruna, Light of Alabaster",colors: ['w', 'u']},
    {name: "Bruna, the Fading Light",colors: ['w']},
    {name: "Bruse Tarl, Boorish Herder",colors: ['r', 'w']},
    {name: "Cabal Patriarch",colors: ['b']},
    {name: "Cao Cao, Lord of Wei",colors: ['b']},
    {name: "Cao Ren, Wei Commander",colors: ['b']},
    {name: "Captain Sisay",colors: ['g', 'w']},
    {name: "Celestial Kirin",colors: ['w']},
    {name: "Chainer, Dementia Master",colors: ['b']},
    {name: "Chandler",colors: ['r']},
    {name: "Chandra, Fire of Kaladesh",colors: ['r']},
    {name: "Child of Alara",colors: ['w', 'u', 'b', 'r', 'g']},
    {name: "Chisei, Heart of Oceans",colors: ['u']},
    {name: "Cho-Manno, Revolutionary",colors: ['w']},
    {name: "Chorus of the Conclave",colors: ['g', 'w']},
    {name: "Chromium",colors: ['w', 'u', 'b']},
    {name: "Circu, Dimir Lobotomist",colors: ['u', 'b']},
    {name: "Cloudhoof Kirin",colors: ['u']},
    {name: "Commander Eesha",colors: ['w']},
    {name: "Commander Greven il-Vec",colors: ['b']},
    {name: "Cromat",colors: ['w', 'u', 'b', 'r', 'g']},
    {name: "Crosis, the Purger",colors: ['u', 'b', 'r']},
    {name: "Crovax, Ascendant Hero",colors: ['w']},
    {name: "Crovax the Cursed",colors: ['b']},
    {name: "Daghatar the Adamant",colors: ['w', 'b', 'g']},
    {name: "Dakkon Blackblade",colors: ['w', 'u', 'b']},
    {name: "Damia, Sage of Stone",colors: ['b', 'g', 'u']},
    {name: "Daretti, Scrap Savant",colors: ['r']},
    {name: "Darien, King of Kjeldor",colors: ['w']},
    {name: "Darigaaz, the Igniter",colors: ['b', 'r', 'g']},
    {name: "Daughter of Autumn",colors: ['g', 'w']},
    {name: "Daxos of Meletis",colors: ['w', 'u']},
    {name: "Daxos the Returned",colors: ['w', 'b']},
    {name: "Depala, Pilot Exemplar",colors: ['r', 'w']},
    {name: "Derevi, Empyrial Tactician",colors: ['g', 'w', 'u']},
    {name: "Diaochan, Artful Beauty",colors: ['r']},
    {name: "Djeru, With Eyes Open",colors: ['w']},
    {name: "Dong Zhou, the Tyrant",colors: ['r']},
    {name: "Doran, the Siege Tower",colors: ['w', 'b', 'g']},
    {name: "Dosan the Falling Leaf",colors: ['g']},
    {name: "Dragonlord Atarka",colors: ['r', 'g']},
    {name: "Dragonlord Dromoka",colors: ['g', 'w']},
    {name: "Dragonlord Kolaghan",colors: ['b', 'r']},
    {name: "Dragonlord Ojutai",colors: ['w', 'u']},
    {name: "Dragonlord Silumgar",colors: ['u', 'b']},
    {name: "Dralnu, Lich Lord",colors: ['u', 'b']},
    {name: "Drana, Kalastria Bloodchief",colors: ['b']},
    {name: "Drana, Liberator of Malakir",colors: ['b']},
    {name: "Dromar, the Banisher",colors: ['w', 'u', 'b']},
    {name: "Dromoka, the Eternal",colors: ['g', 'w']},
    {name: "Dune-Brood Nephilim",colors: ['b', 'r', 'g', 'w']},
    {name: "Dwynen, Gilt-Leaf Daen",colors: ['g']},
    {name: "Edgar Markov",colors: ['r', 'w', 'b']},
    {name: "Edric, Spymaster of Trest",colors: ['g', 'u']},
    {name: "Eight-and-a-Half-Tails",colors: ['w']},
    {name: "Eladamri, Lord of Leaves",colors: ['g']},
    {name: "Elesh Norn, Grand Cenobite",colors: ['w']},
    {name: "Emmara Tandris",colors: ['g', 'w']},
    {name: "Empress Galina",colors: ['u']},
    {name: "Emrakul, the Promised End",colors: ['c']},
    {name: "Endrek Sahr, Master Breeder",colors: ['b']},
    {name: "Ephara, God of the Polis",colors: ['w', 'u']},
    {name: "Erebos, God of the Dead",colors: ['b']},
    {name: "Eron the Relentless",colors: ['r']},
    {name: "Ertai, the Corrupted",colors: ['w', 'u', 'b']},
    {name: "Ertai, Wizard Adept",colors: ['u']},
    {name: "Exava, Rakdos Blood Witch",colors: ['b', 'r']},
    {name: "Experiment Kraj",colors: ['g', 'u']},
    {name: "Ezuri, Claw of Progress",colors: ['g', 'u']},
    {name: "Ezuri, Renegade Leader",colors: ['g']},
    {name: "Feldon of the Third Path",colors: ['r']},
    {name: "Freyalise, Llanowar's Fury",colors: ['g']},
    {name: "Fumiko the Lowblood",colors: ['r']},
    {name: "Gabriel Angelfire",colors: ['g', 'w']},
    {name: "Gaddock Teeg",colors: ['g', 'w']},
    {name: "Gahiji, Honored One",colors: ['r', 'g', 'w']},
    {name: "Gallowbraid",colors: ['b']},
    {name: "Garza Zol, Plague Queen",colors: ['u', 'b', 'r']},
    {name: "Geist of Saint Traft",colors: ['w', 'u']},
    {name: "General Jarkeld",colors: ['w']},
    {name: "General Tazri",colors: ['w', 'u', 'b', 'r', 'g']},
    {name: "Gerrard Capashen",colors: ['w']},
    {name: "Geth, Lord of the Vault",colors: ['b']},
    {name: "Ghave, Guru of Spores",colors: ['w', 'b', 'g']},
    {name: "Ghost Council of Orzhova",colors: ['w', 'b']},
    {name: "Ghoulcaller Gisa",colors: ['b']},
    {name: "Gisa and Geralf",colors: ['u', 'b']},
    {name: "Gisela, Blade of Goldnight",colors: ['r', 'w']},
    {name: "Gisela, the Broken Blade",colors: ['w']},
    {name: "Glint-Eye Nephilim",colors: ['u', 'b', 'r', 'g']},
    {name: "Glissa Sunseeker",colors: ['g']},
    {name: "Glissa, the Traitor",colors: ['b', 'g']},
    {name: "Godo, Bandit Warlord",colors: ['r']},
    {name: "Gonti, Lord of Luxury",colors: ['b']},
    {name: "Gosta Dirk",colors: ['w', 'u']},
    {name: "Grand Arbiter Augustin IV",colors: ['w', 'u']},
    {name: "Grandmother Sengir",colors: ['b']},
    {name: "Greel, Mind Raker",colors: ['b']},
    {name: "Grenzo, Dungeon Warden",colors: ['b', 'r']},
    {name: "Grenzo, Havoc Raiser",colors: ['r']},
    {name: "Grimgrin, Corpse-Born",colors: ['u', 'b']},
    {name: "Guan Yu, Sainted Warrior",colors: ['w']},
    {name: "Gwafa Hazid, Profiteer",colors: ['w', 'u']},
    {name: "Gwendlyn Di Corci",colors: ['u', 'b', 'r']},
    {name: "Haakon, Stromgald Scourge",colors: ['b']},
    {name: "Hakim, Loreweaver",colors: ['u']},
    {name: "Halfdane",colors: ['w', 'u', 'b']},
    {name: "Hanna, Ship's Navigator",colors: ['w', 'u']},
    {name: "Hapatra, Vizier of Poisons",colors: ['b', 'g']},
    {name: "Hazduhr the Abbot",colors: ['w']},
    {name: "Hazezon Tamar",colors: ['r', 'g', 'w']},
    {name: "Hazoret the Fervent",colors: ['r']},
    {name: "Heartless Hidetsugu",colors: ['r']},
    {name: "Heidar, Rimewind Master",colors: ['u']},
    {name: "Heliod, God of the Sun",colors: ['w']},
    {name: "He Who Hungers",colors: ['b']},
    {name: "Higure, the Still Wind",colors: ['u']},
    {name: "Hikari, Twilight Guardian",colors: ['w']},
    {name: "Hisoka, Minamo Sensei",colors: ['u']},
    {name: "Hivis of the Scale",colors: ['r']},
    {name: "Hixus, Prison Warden",colors: ['w']},
    {name: "Hokori, Dust Drinker",colors: ['w']},
    {name: "Homura, Human Ascendant",colors: ['r']},
    {name: "Hope of Ghirapur",colors: ['c']},
    {name: "Horde of Notions",colors: ['w', 'u', 'b', 'r', 'g']},
    {name: "Horobi, Death's Wail",colors: ['b']},
    {name: "Huang Zhong, Shu General",colors: ['w']},
    {name: "Hua Tuo, Honored Physician",colors: ['g']},
    {name: "Hunding Gjornersen",colors: ['w', 'u']},
    {name: "Hythonia the Cruel",colors: ['b']},
    {name: "Ib Halfheart, Goblin Tactician",colors: ['r']},
    {name: "Ihsan's Shade",colors: ['b']},
    {name: "Iizuka the Ruthless",colors: ['r']},
    {name: "Ikra Shidiqi, the Usurper",colors: ['b', 'g']},
    {name: "Inalla, Archmage Ritualist",colors: ['u', 'b', 'r']},
    {name: "Iname as One",colors: ['b', 'g']},
    {name: "Iname, Death Aspect",colors: ['b']},
    {name: "Iname, Life Aspect",colors: ['g']},
    {name: "Infernal Kirin",colors: ['b']},
    {name: "Ink-Eyes, Servant of Oni",colors: ['b']},
    {name: "Ink-Treader Nephilim",colors: ['r', 'g', 'w', 'u']},
    {name: "Intet, the Dreamer",colors: ['g', 'u', 'r']},
    {name: "Iona, Shield of Emeria",colors: ['w']},
    {name: "Irini Sengir",colors: ['b']},
    {name: "Iroas, God of Victory",colors: ['r', 'w']},
    {name: "Isamaru, Hound of Konda",colors: ['w']},
    {name: "Isao, Enlightened Bushi",colors: ['g']},
    {name: "Ishai, Ojutai Dragonspeaker",colors: ['w', 'u']},
    {name: "Ishi-Ishi, Akki Crackshot",colors: ['r']},
    {name: "Ishkanah, Grafwidow",colors: ['b', 'g']},
    {name: "Isperia, Supreme Judge",colors: ['w', 'u']},
    {name: "Isperia the Inscrutable",colors: ['w', 'u']},
    {name: "Ith, High Arcanist",colors: ['w', 'u']},
    {name: "Iwamori of the Open Fist",colors: ['g']},
    {name: "Ixidor, Reality Sculptor",colors: ['u']},
    {name: "Jace, Vryn's Prodigy",colors: ['u']},
    {name: "Jacques le Vert",colors: ['r', 'g', 'w']},
    {name: "Jalira, Master Polymorphist",colors: ['u']},
    {name: "Jarad, Golgari Lich Lord",colors: ['b', 'g']},
    {name: "Jareth, Leonine Titan",colors: ['w']},
    {name: "Jasmine Boreal",colors: ['g', 'w']},
    {name: "Jaya Ballard, Task Mage",colors: ['r']},
    {name: "Jazal Goldmane",colors: ['w']},
    {name: "Jedit Ojanen",colors: ['w', 'u']},
    {name: "Jedit Ojanen of Efrava",colors: ['g']},
    {name: "Jeleva, Nephalia's Scourge",colors: ['u', 'b', 'r']},
    {name: "Jenara, Asura of War",colors: ['g', 'w', 'u']},
    {name: "Jerrard of the Closed Fist",colors: ['r', 'g']},
    {name: "Jeska, Warrior Adept",colors: ['r']},
    {name: "Jhoira of the Ghitu",colors: ['u', 'r']},
    {name: "Jin-Gitaxias, Core Augur",colors: ['u']},
    {name: "Jiwari, the Earth Aflame",colors: ['r']},
    {name: "Johan",colors: ['r', 'g', 'w']},
    {name: "Jolrael, Empress of Beasts",colors: ['g']},
    {name: "Jori En, Ruin Diver",colors: ['u', 'r']},
    {name: "Jor Kadeen, the Prevailer",colors: ['r', 'w']},
    {name: "Joven",colors: ['r']},
    {name: "Jugan, the Rising Star",colors: ['g']},
    {name: "Kaalia of the Vast",colors: ['r', 'w', 'b']},
    {name: "Kaervek the Merciless",colors: ['b', 'r']},
    {name: "Kagemaro, First to Suffer",colors: ['b']},
    {name: "Kaho, Minamo Historian",colors: ['u']},
    {name: "Kalemne, Disciple of Iroas",colors: ['r', 'w']},
    {name: "Kalitas, Bloodchief of Ghet",colors: ['b']},
    {name: "Kalitas, Traitor of Ghet",colors: ['b']},
    {name: "Kamahl, Fist of Krosa",colors: ['g']},
    {name: "Kamahl, Pit Fighter",colors: ['r']},
    {name: "Kambal, Consul of Allocation",colors: ['w', 'b']},
    {name: "Kami of the Crescent Moon",colors: ['u']},
    {name: "Kangee, Aerie Keeper",colors: ['w', 'u']},
    {name: "Karador, Ghost Chieftain",colors: ['w', 'b', 'g']},
    {name: "Karametra, God of Harvests",colors: ['g', 'w']},
    {name: "Kari Zev, Skyship Raider",colors: ['r']},
    {name: "Karlov of the Ghost Council",colors: ['w', 'b']},
    {name: "Karn, Silver Golem",colors: ['c']},
    {name: "Karona, False God",colors: ['w', 'u', 'b', 'r', 'g']},
    {name: "Karrthus, Tyrant of Jund",colors: ['b', 'r', 'g']},
    {name: "Kaseto, Orochi Archmage",colors: ['g', 'u']},
    {name: "Kasimir the Lone Wolf",colors: ['w', 'u']},
    {name: "Kataki, War's Wage",colors: ['w']},
    {name: "Kaysa",colors: ['g']},
    {name: "Kazuul, Tyrant of the Cliffs",colors: ['r']},
    {name: "Kefnet the Mindful",colors: ['u']},
    {name: "Keiga, the Tide Star",colors: ['u']},
    {name: "Kei Takahashi",colors: ['g', 'w']},
    {name: "Kemba, Kha Regent",colors: ['w']},
    {name: "Kentaro, the Smiling Cat",colors: ['w']},
    {name: "Keranos, God of Storms",colors: ['u', 'r']},
    {name: "Kess, Dissident Mage",colors: ['u', 'b', 'r']},
    {name: "Kiki-Jiki, Mirror Breaker",colors: ['r']},
    {name: "Kiku, Night's Flower",colors: ['b']},
    {name: "King Macar, the Gold-Cursed",colors: ['b']},
    {name: "Kira, Great Glass-Spinner",colors: ['u']},
    {name: "Kiyomaro, First to Stand",colors: ['w']},
    {name: "Kodama of the Center Tree",colors: ['g']},
    {name: "Kodama of the North Tree",colors: ['g']},
    {name: "Kodama of the South Tree",colors: ['g']},
    {name: "Kokusho, the Evening Star",colors: ['b']},
    {name: "Kolaghan, the Storm's Fury",colors: ['b', 'r']},
    {name: "Konda, Lord of Eiganjo",colors: ['w']},
    {name: "Kongming, \"Sleeping Dragon\"",colors: ['w']},
    {name: "Korlash, Heir to Blackblade",colors: ['b']},
    {name: "Kothophed, Soul Hoarder",colors: ['b']},
    {name: "Kozilek, Butcher of Truth",colors: ['c']},
    {name: "Kozilek, the Great Distortion",colors: ['c']},
    {name: "Kraum, Ludevic's Opus",colors: ['u', 'r']},
    {name: "Krenko, Mob Boss",colors: ['r']},
    {name: "Kresh the Bloodbraided",colors: ['b', 'r', 'g']},
    {name: "Krond the Dawn-Clad",colors: ['g', 'w']},
    {name: "Kruphix, God of Horizons",colors: ['g', 'u']},
    {name: "Kumano, Master Yamabushi",colors: ['r']},
    {name: "Kuon, Ogre Ascendant",colors: ['b']},
    {name: "Kurkesh, Onakke Ancient",colors: ['r']},
    {name: "Kuro, Pitlord",colors: ['b']},
    {name: "Kydele, Chosen of Kruphix",colors: ['g', 'u']},
    {name: "Kynaios and Tiro of Meletis",colors: ['r', 'g', 'w', 'u']},
    {name: "Kyoki, Sanity's Eclipse",colors: ['b']},
    {name: "Kytheon, Hero of Akros",colors: ['w']},
    {name: "Lady Caleria",colors: ['g', 'w']},
    {name: "Lady Evangela",colors: ['w', 'u', 'b']},
    {name: "Lady Orca",colors: ['b', 'r']},
    {name: "Lady Sun",colors: ['u']},
    {name: "Lady Zhurong, Warrior Queen",colors: ['g']},
    {name: "Latulla, Keldon Overseer",colors: ['r']},
    {name: "Lavinia of the Tenth",colors: ['w', 'u']},
    {name: "Lazav, Dimir Mastermind",colors: ['u', 'b']},
    {name: "Licia, Sanguine Tribune",colors: ['r', 'w', 'b']},
    {name: "Lieutenant Kirtar",colors: ['w']},
    {name: "Liliana, Heretical Healer",colors: ['b']},
    {name: "Lim-Dul the Necromancer",colors: ['b']},
    {name: "Linessa, Zephyr Mage",colors: ['u']},
    {name: "Lin Sivvi, Defiant Hero",colors: ['w']},
    {name: "Linvala, Keeper of Silence",colors: ['w']},
    {name: "Linvala, the Preserver",colors: ['w']},
    {name: "Liu Bei, Lord of Shu",colors: ['w']},
    {name: "Livonya Silone",colors: ['r', 'g']},
    {name: "Llawan, Cephalid Empress",colors: ['u']},
    {name: "Lord Magnus",colors: ['g', 'w']},
    {name: "Lord of Tresserhorn",colors: ['u', 'b', 'r']},
    {name: "Lorthos, the Tidemaker",colors: ['u']},
    {name: "Lovisa Coldeyes",colors: ['r']},
    {name: "Lu Bu, Master-at-Arms",colors: ['r']},
    {name: "Ludevic, Necro-Alchemist",colors: ['u', 'r']},
    {name: "Lu Meng, Wu General",colors: ['u']},
    {name: "Lu Su, Wu Advisor",colors: ['u']},
    {name: "Lu Xun, Scholar General",colors: ['u']},
    {name: "Lyzolda, the Blood Witch",colors: ['b', 'r']},
    {name: "Ma Chao, Western Warrior",colors: ['r']},
    {name: "Maelstrom Wanderer",colors: ['g', 'u', 'r']},
    {name: "Maga, Traitor to Mortals",colors: ['b']},
    {name: "Mageta the Lion",colors: ['w']},
    {name: "Mairsil, the Pretender",colors: ['u', 'b', 'r']},
    {name: "Major Teroh",colors: ['w']},
    {name: "Malfegor",colors: ['b', 'r']},
    {name: "Mangara of Corondor",colors: ['w']},
    {name: "Mannichi, the Fevered Dream",colors: ['r']},
    {name: "Maralen of the Mornsong",colors: ['b']},
    {name: "Marath, Will of the Wild",colors: ['r', 'g', 'w']},
    {name: "Maraxus of Keld",colors: ['r']},
    {name: "Marchesa, the Black Rose",colors: ['u', 'b', 'r']},
    {name: "Marhault Elsdragon",colors: ['r', 'g']},
    {name: "Marrow-Gnawer",colors: ['b']},
    {name: "Marton Stromgald",colors: ['r']},
    {name: "Masako the Humorless",colors: ['w']},
    {name: "Masumaro, First to Live",colors: ['g']},
    {name: "Mathas, Fiend Seeker",colors: ['r', 'w', 'b']},
    {name: "Mayael the Anima",colors: ['r', 'g', 'w']},
    {name: "Mazirek, Kraul Death Priest",colors: ['b', 'g']},
    {name: "Medomai the Ageless",colors: ['w', 'u']},
    {name: "Melek, Izzet Paragon",colors: ['u', 'r']},
    {name: "Melira, Sylvok Outcast",colors: ['g']},
    {name: "Meloku the Clouded Mirror",colors: ['u']},
    {name: "Memnarch",colors: ['u']},
    {name: "Meng Huo, Barbarian King",colors: ['g']},
    {name: "Meren of Clan Nel Toth",colors: ['b', 'g']},
    {name: "Merieke Ri Berit",colors: ['w', 'u', 'b']},
    {name: "Michiko Konda, Truth Seeker",colors: ['w']},
    {name: "Mikaeus, the Lunarch",colors: ['w']},
    {name: "Mikaeus, the Unhallowed",colors: ['b']},
    {name: "Mina and Denn, Wildborn",colors: ['r', 'g']},
    {name: "Mirko Vosk, Mind Drinker",colors: ['u', 'b']},
    {name: "Mirri, Cat Warrior",colors: ['g']},
    {name: "Mirri the Cursed",colors: ['b']},
    {name: "Mirri, Weatherlight Duelist",colors: ['g', 'w']},
    {name: "Mishra, Artificer Prodigy",colors: ['u', 'b', 'r']},
    {name: "Mistform Ultimus",colors: ['u']},
    {name: "Mizzix of the Izmagnus",colors: ['u', 'r']},
    {name: "Mogis, God of Slaughter",colors: ['b', 'r']},
    {name: "Molimo, Maro-Sorcerer",colors: ['g']},
    {name: "Momir Vig, Simic Visionary",colors: ['g', 'u']},
    {name: "Morinfen",colors: ['b']},
    {name: "Multani, Maro-Sorcerer",colors: ['g']},
    {name: "Munda, Ambush Leader",colors: ['r', 'w']},
    {name: "Muzzio, Visionary Architect",colors: ['u']},
    {name: "Myojin of Cleansing Fire",colors: ['w']},
    {name: "Myojin of Infinite Rage",colors: ['r']},
    {name: "Myojin of Life's Web",colors: ['g']},
    {name: "Myojin of Night's Reach",colors: ['b']},
    {name: "Myojin of Seeing Winds",colors: ['u']},
    {name: "Nagao, Bound by Honor",colors: ['w']},
    {name: "Nahiri, the Lithomancer",colors: ['w']},
    {name: "Narset, Enlightened Master",colors: ['u', 'r', 'w']},
    {name: "Nath of the Gilt-Leaf",colors: ['b', 'g']},
    {name: "Nazahn, Revered Bladesmith",colors: ['g', 'w']},
    {name: "Nebuchadnezzar",colors: ['u', 'b']},
    {name: "Nefarox, Overlord of Grixis",colors: ['b']},
    {name: "Neheb, the Eternal",colors: ['r']},
    {name: "Neheb, the Worthy",colors: ['b', 'r']},
    {name: "Nekusar, the Mindrazer",colors: ['u', 'b', 'r']},
    {name: "Nemata, Grove Guardian",colors: ['g']},
    {name: "Nicol Bolas",colors: ['u', 'b', 'r']},
    {name: "Nin, the Pain Artist",colors: ['u', 'r']},
    {name: "Nissa, Vastwood Seer",colors: ['g']},
    {name: "Niv-Mizzet, Dracogenius",colors: ['u', 'r']},
    {name: "Niv-Mizzet, the Firemind",colors: ['u', 'r']},
    {name: "Norin the Wary",colors: ['r']},
    {name: "Noyan Dar, Roil Shaper",colors: ['w', 'u']},
    {name: "Numot, the Devastator",colors: ['u', 'r', 'w']},
    {name: "Nylea, God of the Hunt",colors: ['g']},
    {name: "Ob Nixilis of the Black Oath",colors: ['b']},
    {name: "Ob Nixilis, the Fallen",colors: ['b']},
    {name: "Ob Nixilis, Unshackled",colors: ['b']},
    {name: "Obzedat, Ghost Council",colors: ['w', 'b']},
    {name: "Odric, Lunarch Marshal",colors: ['w']},
    {name: "Odric, Master Tactician",colors: ['w']},
    {name: "Ojutai, Soul of Winter",colors: ['w', 'u']},
    {name: "O-Kagachi, Vengeful Kami",colors: ['w', 'u', 'b', 'r', 'g']},
    {name: "Oketra the True",colors: ['w']},
    {name: "Olivia, Mobilized for War",colors: ['b', 'r']},
    {name: "Olivia Voldaren",colors: ['b', 'r']},
    {name: "Oloro, Ageless Ascetic",colors: ['w', 'u', 'b']},
    {name: "Omnath, Locus of Mana",colors: ['g']},
    {name: "Omnath, Locus of Rage",colors: ['r', 'g']},
    {name: "Oona, Queen of the Fae",colors: ['u', 'b']},
    {name: "Opal-Eye, Konda's Yojimbo",colors: ['w']},
    {name: "Orim, Samite Healer",colors: ['w']},
    {name: "Oriss, Samite Guardian",colors: ['w']},
    {name: "Oros, the Avenger",colors: ['r', 'w', 'b']},
    {name: "Oviya Pashiri, Sage Lifecrafter",colors: ['g']},
    {name: "Oyobi, Who Split the Heavens",colors: ['w']},
    {name: "Padeem, Consul of Innovation",colors: ['u']},
    {name: "Palladia-Mors",colors: ['r', 'g', 'w']},
    {name: "Pang Tong, \"Young Phoenix\"",colors: ['w']},
    {name: "Patron of the Akki",colors: ['r']},
    {name: "Patron of the Kitsune",colors: ['w']},
    {name: "Patron of the Moon",colors: ['u']},
    {name: "Patron of the Nezumi",colors: ['b']},
    {name: "Patron of the Orochi",colors: ['g']},
    {name: "Pavel Maliki",colors: ['b', 'r']},
    {name: "Phage the Untouchable",colors: ['b']},
    {name: "Pharika, God of Affliction",colors: ['b', 'g']},
    {name: "Phelddagrif",colors: ['g', 'w', 'u']},
    {name: "Phenax, God of Deception",colors: ['u', 'b']},
    {name: "Pia and Kiran Nalaar",colors: ['r']},
    {name: "Pia Nalaar",colors: ['r']},
    {name: "Pianna, Nomad Captain",colors: ['w']},
    {name: "Polukranos, World Eater",colors: ['g']},
    {name: "Prime Speaker Zegana",colors: ['g', 'u']},
    {name: "Princess Lucrezia",colors: ['u', 'b']},
    {name: "Progenitus",colors: ['w', 'u', 'b', 'r', 'g']},
    {name: "Prossh, Skyraider of Kher",colors: ['b', 'r', 'g']},
    {name: "Purphoros, God of the Forge",colors: ['r']},
    {name: "Purraj of Urborg",colors: ['b']},
    {name: "Queen Marchesa",colors: ['r', 'w', 'b']},
    {name: "Radha, Heir to Keld",colors: ['r', 'g']},
    {name: "Radiant, Archangel",colors: ['w']},
    {name: "Rafiq of the Many",colors: ['g', 'w', 'u']},
    {name: "Ragnar",colors: ['g', 'w', 'u']},
    {name: "Rakdos, Lord of Riots",colors: ['b', 'r']},
    {name: "Rakdos the Defiler",colors: ['b', 'r']},
    {name: "Rakka Mar",colors: ['r']},
    {name: "Raksha Golden Cub",colors: ['w']},
    {name: "Ramirez DePietro",colors: ['u', 'b']},
    {name: "Ramos, Dragon Engine",colors: ['w', 'u', 'b', 'r', 'g']},
    {name: "Ramses Overdark",colors: ['u', 'b']},
    {name: "Rashida Scalebane",colors: ['w']},
    {name: "Rashka the Slayer",colors: ['w']},
    {name: "Rashmi, Eternities Crafter",colors: ['g', 'u']},
    {name: "Rasputin Dreamweaver",colors: ['w', 'u']},
    {name: "Ravos, Soultender",colors: ['w', 'b']},
    {name: "Rayne, Academy Chancellor",colors: ['u']},
    {name: "Razaketh, the Foulblooded",colors: ['b']},
    {name: "Razia, Boros Archangel",colors: ['r', 'w']},
    {name: "Reaper King",colors: ['w', 'u', 'b', 'r', 'g']},
    {name: "Reki, the History of Kamigawa",colors: ['g']},
    {name: "Reveka, Wizard Savant",colors: ['u']},
    {name: "Reya Dawnbringer",colors: ['w']},
    {name: "Reyhan, Last of the Abzan",colors: ['b', 'g']},
    {name: "Rhonas the Indomitable",colors: ['g']},
    {name: "Rhys the Exiled",colors: ['b', 'g']},
    {name: "Rhys the Redeemed",colors: ['g', 'w']},
    {name: "Riku of Two Reflections",colors: ['g', 'u', 'r']},
    {name: "Rishkar, Peema Renegade",colors: ['g']},
    {name: "Rith, the Awakener",colors: ['r', 'g', 'w']},
    {name: "Riven Turnbull",colors: ['u', 'b']},
    {name: "Rohgahh of Kher Keep",colors: ['b', 'r']},
    {name: "Roon of the Hidden Realm",colors: ['g', 'w', 'u']},
    {name: "Rorix Bladewing",colors: ['r']},
    {name: "Rosheen Meanderer",colors: ['r', 'g']},
    {name: "Rubinia Soulsinger",colors: ['g', 'w', 'u']},
    {name: "Ruhan of the Fomori",colors: ['u', 'r', 'w']},
    {name: "Rune-Tail, Kitsune Ascendant",colors: ['w']},
    {name: "Ruric Thar, the Unbowed",colors: ['r', 'g']},
    {name: "Ryusei, the Falling Star",colors: ['r']},
    {name: "Sachi, Daughter of Seshiro",colors: ['g']},
    {name: "Saffi Eriksdotter",colors: ['g', 'w']},
    {name: "Sakashima the Impostor",colors: ['u']},
    {name: "Sakiko, Mother of Summer",colors: ['g']},
    {name: "Samut, Voice of Dissent",colors: ['r', 'g', 'w']},
    {name: "Sapling of Colfenor",colors: ['b', 'g']},
    {name: "Sasaya, Orochi Ascendant",colors: ['g']},
    {name: "Saskia the Unyielding",colors: ['b', 'r', 'g', 'w']},
    {name: "Savra, Queen of the Golgari",colors: ['b', 'g']},
    {name: "Scion of the Ur-Dragon",colors: ['w', 'u', 'b', 'r', 'g']},
    {name: "Sedris, the Traitor King",colors: ['u', 'b', 'r']},
    {name: "Seizan, Perverter of Truth",colors: ['b']},
    {name: "Sekki, Seasons' Guide",colors: ['g']},
    {name: "Sek'Kuar, Deathkeeper",colors: ['b', 'r', 'g']},
    {name: "Selenia, Dark Angel",colors: ['w', 'b']},
    {name: "Selvala, Explorer Returned",colors: ['g', 'w']},
    {name: "Selvala, Heart of the Wilds",colors: ['g']},
    {name: "Sensei Golden-Tail",colors: ['w']},
    {name: "Sen Triplets",colors: ['w', 'u', 'b']},
    {name: "Seshiro the Anointed",colors: ['g']},
    {name: "Seton, Krosan Protector",colors: ['g']},
    {name: "Sharuum the Hegemon",colors: ['w', 'u', 'b']},
    {name: "Shattergang Brothers",colors: ['b', 'r', 'g']},
    {name: "Shauku, Endbringer",colors: ['b']},
    {name: "Sheoldred, Whispering One",colors: ['b']},
    {name: "Shimatsu the Bloodcloaked",colors: ['r']},
    {name: "Shirei, Shizo's Caretaker",colors: ['b']},
    {name: "Shisato, Whispering Hunter",colors: ['g']},
    {name: "Shizuko, Caller of Autumn",colors: ['g']},
    {name: "Shu Yun, the Silent Tempest",colors: ['u', 'r', 'w']},
    {name: "Sidar Jabari",colors: ['w']},
    {name: "Sidar Kondo of Jamuraa",colors: ['g', 'w']},
    {name: "Sidisi, Brood Tyrant",colors: ['b', 'g', 'u']},
    {name: "Sidisi, Undead Vizier",colors: ['b']},
    {name: "Sigarda, Heron's Grace",colors: ['g', 'w']},
    {name: "Sigarda, Host of Herons",colors: ['g', 'w']},
    {name: "Silas Renn, Seeker Adept",colors: ['u', 'b']},
    {name: "Silumgar, the Drifting Death",colors: ['u', 'b']},
    {name: "Silvos, Rogue Elemental",colors: ['g']},
    {name: "Sima Yi, Wei Field Marshal",colors: ['b']},
    {name: "Sir Shandlar of Eberyn",colors: ['g', 'w']},
    {name: "Sisters of Stone Death",colors: ['b', 'g']},
    {name: "Sivitri Scarzam",colors: ['u', 'b']},
    {name: "Skeleton Ship",colors: ['u', 'b']},
    {name: "Skithiryx, the Blight Dragon",colors: ['b']},
    {name: "Skullbriar, the Walking Grave",colors: ['b', 'g']},
    {name: "Skyfire Kirin",colors: ['r']},
    {name: "Sliver Hivelord",colors: ['w', 'u', 'b', 'r', 'g']},
    {name: "Sliver Legion",colors: ['w', 'u', 'b', 'r', 'g']},
    {name: "Sliver Overlord",colors: ['w', 'u', 'b', 'r', 'g']},
    {name: "Sliver Queen",colors: ['w', 'u', 'b', 'r', 'g']},
    {name: "Slobad, Goblin Tinkerer",colors: ['r']},
    {name: "Sol'kanar the Swamp King",colors: ['u', 'b', 'r']},
    {name: "Soramaro, First to Dream",colors: ['u']},
    {name: "Soraya the Falconer",colors: ['w']},
    {name: "Sosuke, Son of Seshiro",colors: ['g']},
    {name: "Spirit of the Night",colors: ['b']},
    {name: "Squee, Goblin Nabob",colors: ['r']},
    {name: "Sram, Senior Edificer",colors: ['w']},
    {name: "Stangg",colors: ['r', 'g']},
    {name: "Starke of Rath",colors: ['r']},
    {name: "Stitcher Geralf",colors: ['u']},
    {name: "Stonebrow, Krosan Hero",colors: ['r', 'g']},
    {name: "Sunastian Falconer",colors: ['r', 'g']},
    {name: "Sun Ce, Young Conquerer",colors: ['u']},
    {name: "Sun Quan, Lord of Wu",colors: ['u']},
    {name: "Surrak Dragonclaw",colors: ['g', 'u', 'r']},
    {name: "Surrak, the Hunt Caller",colors: ['g']},
    {name: "Sydri, Galvanic Genius",colors: ['w', 'u', 'b']},
    {name: "Sygg, River Cutthroat",colors: ['u', 'b']},
    {name: "Sygg, River Guide",colors: ['w', 'u']},
    {name: "Szadek, Lord of Secrets",colors: ['u', 'b']},
    {name: "Tahngarth, Talruum Hero",colors: ['r']},
    {name: "Taigam, Ojutai Master",colors: ['w', 'u']},
    {name: "Taigam, Sidisi's Hand",colors: ['u', 'b']},
    {name: "Tajic, Blade of the Legion",colors: ['r', 'w']},
    {name: "Takeno, Samurai General",colors: ['w']},
    {name: "Talrand, Sky Summoner",colors: ['u']},
    {name: "Tana, the Bloodsower",colors: ['r', 'g']},
    {name: "Taniwha",colors: ['u']},
    {name: "Tariel, Reckoner of Souls",colors: ['r', 'w', 'b']},
    {name: "Tarox Bladewing",colors: ['r']},
    {name: "Tasigur, the Golden Fang",colors: ['b', 'g', 'u']},
    {name: "Teferi, Mage of Zhalfir",colors: ['u']},
    {name: "Teferi, Temporal Archmage",colors: ['u']},
    {name: "Telim'Tor",colors: ['r']},
    {name: "Temmet, Vizier of Naktamun",colors: ['w', 'u']},
    {name: "Teneb, the Harvester",colors: ['w', 'b', 'g']},
    {name: "Tetsuo Umezawa",colors: ['u', 'b', 'r']},
    {name: "Teysa, Envoy of Ghosts",colors: ['w', 'b']},
    {name: "Teysa, Orzhov Scion",colors: ['w', 'b']},
    {name: "Thada Adel, Acquisitor",colors: ['u']},
    {name: "Thalia, Guardian of Thraben",colors: ['w']},
    {name: "Thalia, Heretic Cathar",colors: ['w']},
    {name: "Thassa, God of the Sea",colors: ['u']},
    {name: "The Gitrog Monster",colors: ['b', 'g']},
    {name: "The Lady of the Mountain",colors: ['r', 'g']},
    {name: "The Locust God",colors: ['u', 'r']},
    {name: "Thelon of Havenwood",colors: ['b', 'g']},
    {name: "The Mimeoplasm",colors: ['b', 'g', 'u']},
    {name: "The Scarab God",colors: ['u', 'b']},
    {name: "The Scorpion God",colors: ['b', 'r']},
    {name: "The Unspeakable",colors: ['u']},
    {name: "The Ur-Dragon",colors: ['w', 'u', 'b', 'r', 'g']},
    {name: "Thrasios, Triton Hero",colors: ['g', 'u']},
    {name: "Thraximundar",colors: ['u', 'b', 'r']},
    {name: "Thriss, Nantuko Primus",colors: ['g']},
    {name: "Thromok the Insatiable",colors: ['r', 'g']},
    {name: "Thrun, the Last Troll",colors: ['g']},
    {name: "Tibor and Lumia",colors: ['u', 'r']},
    {name: "Titania, Protector of Argoth",colors: ['g']},
    {name: "Tivadar of Thorn",colors: ['w']},
    {name: "Tobias Andrion",colors: ['w', 'u']},
    {name: "Tolsimir Wolfblood",colors: ['g', 'w']},
    {name: "Tomorrow, Azami's Familiar",colors: ['u']},
    {name: "Torsten Von Ursus",colors: ['g', 'w']},
    {name: "Tor Wauki",colors: ['b', 'r']},
    {name: "Toshiro Umezawa",colors: ['b']},
    {name: "Treva, the Renewer",colors: ['g', 'w', 'u']},
    {name: "Triad of Fates",colors: ['w', 'b']},
    {name: "Tromokratis",colors: ['u']},
    {name: "Trostani, Selesnya's Voice",colors: ['g', 'w']},
    {name: "Tsabo Tavoc",colors: ['b', 'r']},
    {name: "Tuknir Deathlock",colors: ['r', 'g']},
    {name: "Tuktuk the Explorer",colors: ['r']},
    {name: "Tymaret, the Murder King",colors: ['b', 'r']},
    {name: "Tymna the Weaver",colors: ['w', 'b']},
    {name: "Ulamog, the Ceaseless Hunger",colors: ['c']},
    {name: "Ulamog, the Infinite Gyre",colors: ['c']},
    {name: "Ulasht, the Hate Seed",colors: ['r', 'g']},
    {name: "Ulrich of the Krallenhorde",colors: ['r', 'g']},
    {name: "Unesh, Criosphinx Sovereign",colors: ['u']},
    {name: "Urabrask the Hidden",colors: ['r']},
    {name: "Ur-Drago",colors: ['u', 'b']},
    {name: "Uril, the Miststalker",colors: ['r', 'g', 'w']},
    {name: "Uyo, Silent Prophet",colors: ['u']},
    {name: "Vaevictis Asmadi",colors: ['b', 'r', 'g']},
    {name: "Varolz, the Scar-Striped",colors: ['b', 'g']},
    {name: "Vela the Night-Clad",colors: ['u', 'b']},
    {name: "Veldrane of Sengir",colors: ['b']},
    {name: "Vendilion Clique",colors: ['u']},
    {name: "Venser, Shaper Savant",colors: ['u']},
    {name: "Verdeloth the Ancient",colors: ['g']},
    {name: "Vhati il-Dal",colors: ['b', 'g']},
    {name: "Vial Smasher the Fierce",colors: ['b', 'r']},
    {name: "Visara the Dreadful",colors: ['b']},
    {name: "Vish Kal, Blood Arbiter",colors: ['w', 'b']},
    {name: "Volrath the Fallen",colors: ['b']},
    {name: "Vorel of the Hull Clade",colors: ['g', 'u']},
    {name: "Vorinclex, Voice of Hunger",colors: ['g']},
    {name: "Vorosh, the Hunter",colors: ['b', 'g', 'u']},
    {name: "Wasitora, Nekoru Queen",colors: ['b', 'r', 'g']},
    {name: "Witch-Maw Nephilim",colors: ['g', 'w', 'u', 'b']},
    {name: "Wort, Boggart Auntie",colors: ['b', 'r']},
    {name: "Wort, the Raidmother",colors: ['r', 'g']},
    {name: "Wrexial, the Risen Deep",colors: ['u', 'b']},
    {name: "Wydwen, the Biting Gale",colors: ['u', 'b']},
    {name: "Xenagos, God of Revels",colors: ['r', 'g']},
    {name: "Xiahou Dun, the One-Eyed",colors: ['b']},
    {name: "Xira Arien",colors: ['b', 'r', 'g']},
    {name: "Xun Yu, Wei Advisor",colors: ['b']},
    {name: "Yahenni, Undying Partisan",colors: ['b']},
    {name: "Yasova Dragonclaw",colors: ['g', 'u', 'r']},
    {name: "Yeva, Nature's Herald",colors: ['g']},
    {name: "Yidris, Maelstrom Wielder",colors: ['u', 'b', 'r', 'g']},
    {name: "Yisan, the Wanderer Bard",colors: ['g']},
    {name: "Yomiji, Who Bars the Way",colors: ['w']},
    {name: "Yore-Tiller Nephilim",colors: ['w', 'u', 'b', 'r']},
    {name: "Yosei, the Morning Star",colors: ['w']},
    {name: "Yuan Shao, the Indecisive",colors: ['r']},
    {name: "Yukora, the Prisoner",colors: ['b']},
    {name: "Zada, Hedron Grinder",colors: ['r']},
    {name: "Zedruu the Greathearted",colors: ['u', 'r', 'w']},
    {name: "Zhang Fei, Fierce Warrior",colors: ['w']},
    {name: "Zhang He, Wei General",colors: ['b']},
    {name: "Zhang Liao, Hero of Hefei",colors: ['b']},
    {name: "Zhao Zilong, Tiger General",colors: ['w']},
    {name: "Zhou Yu, Chief Commander",colors: ['u']},
    {name: "Zhuge Jin, Wu Strategist",colors: ['u']},
    {name: "Zirilan of the Claw",colors: ['r']},
    {name: "Zo-Zu the Punisher",colors: ['r']},
    {name: "Zuberi, Golden Feather",colors: ['w']},
    {name: "Zuo Ci, the Mocking Sage",colors: ['g']},
    {name: "Zurgo Bellstriker",colors: ['r']},
    {name: "Zurgo Helmsmasher",colors: ['r', 'w', 'b']},
    {name: "Zur the Enchanter",colors: ['w', 'u', 'b']}
  ]
}

export default {
  namespaced,
  state
}