const namespaced = true

const state = {
  commandersList: [    
    {name: "Aboshan, Cephalid Emperor", nickname: "Aboshan", colors: ['u']},
    {name: "Adamaro, First to Desire", nickname: "Adamaro", colors: ['r']},
    {name: "Adriana, Captain of the Guard", nickname: "Adriana", colors: ['r', 'w']},
    {name: "Adun Oakenshield", nickname: "Adun", colors: ['b', 'r', 'g']},
    {name: "Agrus Kos, Wojek Veteran", nickname: "Agrus Kos", colors: ['r', 'w']},
    {name: "Akiri, Line-Slinger", nickname: "Akiri", colors: ['r', 'w']},
    {name: "Akroma, Angel of Fury", nickname: "Akroma", colors: ['r']},
    {name: "Akroma, Angel of Wrath", nickname: "Akroma", colors: ['w']},
    {name: "Akuta, Born of Ash", nickname: "Akuta", colors: ['b']},
    {name: "Alesha, Who Smiles at Death", nickname: "Alesha", colors: ['r', 'w', 'b']},
    {name: "Alexi, Zephyr Mage", nickname: "Alexi", colors: ['u']},
    {name: "Alhammarret, High Arbiter", nickname: "Alhammarret", colors: ['u']},
    {name: "Ambassador Laquatus", nickname: "Laquatus", colors: ['u']},
    {name: "Anafenza, Kin-Tree Spirit", nickname: "Anafenza", colors: ['w']},
    {name: "Anafenza, the Foremost", nickname: "Anafenza", colors: ['w', 'b', 'g']},
    {name: "Anax and Cymede", nickname: "Anax & Cymede", colors: ['r', 'w']},
    {name: "Angus Mackenzie", nickname: "Angus", colors: ['g', 'w', 'u']},
    {name: "Animar, Soul of Elements", nickname: "Animar", colors: ['g', 'u', 'r']},
    {name: "Anowon, the Ruin Sage", nickname: "Anowon", colors: ['b']},
    {name: "Anthousa, Setessan Hero", nickname: "Anthousa", colors: ['g']},
    {name: "Anya, Merciless Angel", nickname: "Anya", colors: ['r', 'w']},
    {name: "Arahbo, Roar of the World", nickname: "Arahbo", colors: ['g', 'w']},
    {name: "Arashi, the Sky Asunder", nickname: "Arashi", colors: ['g']},
    {name: "Arcades Sabboth", nickname: "Arcades", colors: ['g', 'w', 'u']},
    {name: "Arcanis the Omnipotent", nickname: "Arcanis", colors: ['u']},
    {name: "Archangel Avacyn", nickname: "Avacyn", colors: ['r', 'w']},
    {name: "Arcum Dagsson", nickname: "Arcum Dagsson", colors: ['u']},
    {name: "Arjun, the Shifting Flame", nickname: "Arjun", colors: ['u', 'r']},
    {name: "Ascendant Evincar", nickname: "Evincar", colors: ['b']},
    {name: "Ashling, the Extinguisher", nickname: "Ashling", colors: ['b']},
    {name: "Ashling the Pilgrim", nickname: "Ashling", colors: ['r']},
    {name: "Asmira, Holy Avenger", nickname: "Asmira", colors: ['g', 'w']},
    {name: "Atalya, Samite Master", nickname: "Atalya", colors: ['w']},
    {name: "Atarka, World Render", nickname: "Atarka", colors: ['r', 'g']},
    {name: "Athreos, God of Passage", nickname: "Athreos", colors: ['w', 'b']},
    {name: "Atogatog", nickname: "Atogatog", colors: ['w', 'u', 'b', 'r', 'g']},
    {name: "Atraxa, Praetors' Voice", nickname: "Atraxa", colors: ['g', 'w', 'u', 'b']},
    {name: "Aurelia, the Warleader", nickname: "Aurelia", colors: ['r', 'w']},
    {name: "Autumn Willow", nickname: "Autumn Willow", colors: ['g']},
    {name: "Avacyn, Angel of Hope", nickname: "Avacyn", colors: ['w']},
    {name: "Avacyn, Guardian Angel", nickname: "Avacyn", colors: ['w']},
    {name: "Avacyn, the Purifier", nickname: "Avacyn", colors: ['r', 'w']},
    {name: "Axelrod Gunnarson", nickname: "Axelrod", colors: ['b', 'r']},
    {name: "Ayesha Tanaka", nickname: "Ayesha Tanaka", colors: ['w', 'u']},
    {name: "Ayli, Eternal Pilgrim", nickname: "Ayli", colors: ['w', 'b']},
    {name: "Ayumi, the Last Visitor", nickname: "Ayumi", colors: ['g']},
    {name: "Azami, Lady of Scrolls", nickname: "Azami", colors: ['u']},
    {name: "Azusa, Lost but Seeking", nickname: "Azusa", colors: ['g']},
    {name: "Balan, Wandering Knight", nickname: "Balan", colors: ['w']},
    {name: "Balthor the Defiled", nickname: "Balthor", colors: ['b']},
    {name: "Balthor the Stout", nickname: "Balthor", colors: ['r']},
    {name: "Baral, Chief of Compliance", nickname: "Baral", colors: ['u']},
    {name: "Barktooth Warbeard", nickname: "Barktooth", colors: ['b', 'r']},
    {name: "Baron Sengir", nickname: "Baron Sengir", colors: ['b']},
    {name: "Barrin, Master Wizard", nickname: "Barrin", colors: ['u']},
    {name: "Bartel Runeaxe", nickname: "Bartel Runeaxe", colors: ['b', 'r', 'g']},
    {name: "Baru, Fist of Krosa", nickname: "Baru", colors: ['g']},
    {name: "Basandra, Battle Seraph", nickname: "Basandra", colors: ['r', 'w']},
    {name: "Ben-Ben, Akki Hermit", nickname: "Ben-Ben", colors: ['r']},
    {name: "Bladewing the Risen", nickname: "Bladewing", colors: ['b', 'r']},
    {name: "Blind Seer", nickname: "Blind Seer", colors: ['u']},
    {name: "Bontu the Glorified", nickname: "Bontu", colors: ['b']},
    {name: "Borborygmos", nickname: "Borborygmos", colors: ['r', 'g']},
    {name: "Borborygmos Enraged", nickname: "Borborygmos", colors: ['r', 'g']},
    {name: "Boris Devilboon", nickname: "Boris", colors: ['b', 'r']},
    {name: "Bosh, Iron Golem", nickname: "Bosh", colors: ['r']},
    {name: "Bounteous Kirin", nickname: "Bounteous", colors: ['g']},
    {name: "Brago, King Eternal", nickname: "Brago", colors: ['w', 'u']},
    {name: "Braids, Conjurer Adept", nickname: "Braids", colors: ['u']},
    {name: "Breya, Etherium Shaper", nickname: "Breya", colors: ['w', 'u', 'b', 'r']},
    {name: "Brigid, Hero of Kinsbaile", nickname: "Brigid", colors: ['w']},
    {name: "Brimaz, King of Oreskos", nickname: "Brimaz", colors: ['w']},
    {name: "Brion Stoutarm", nickname: "Brion Stoutarm", colors: ['r', 'w']},
    {name: "Brothers Yamazaki", nickname: "Yamazaki", colors: ['r']},
    {name: "Bruna, Light of Alabaster", nickname: "Bruna", colors: ['w', 'u']},
    {name: "Bruna, the Fading Light", nickname: "Bruna", colors: ['w']},
    {name: "Bruse Tarl, Boorish Herder", nickname: "Bruse Tarl", colors: ['r', 'w']},
    {name: "Cabal Patriarch", nickname: "Patriarch", colors: ['b']},
    {name: "Cao Cao, Lord of Wei", nickname: "Cao Cao", colors: ['b']},
    {name: "Cao Ren, Wei Commander", nickname: "Cao Ren", colors: ['b']},
    {name: "Captain Sisay", nickname: "Captain Sisay", colors: ['g', 'w']},
    {name: "Celestial Kirin", nickname: "Celestial", colors: ['w']},
    {name: "Chainer, Dementia Master", nickname: "Chainer", colors: ['b']},
    {name: "Chandler", nickname: "Chandler", colors: ['r']},
    {name: "Chandra, Fire of Kaladesh", nickname: "Chandra", colors: ['r']},
    {name: "Child of Alara", nickname: "Child of Alara", colors: ['w', 'u', 'b', 'r', 'g']},
    {name: "Chisei, Heart of Oceans", nickname: "Chisei", colors: ['u']},
    {name: "Cho-Manno, Revolutionary", nickname: "Cho-Manno", colors: ['w']},
    {name: "Chorus of the Conclave", nickname: "Chorus", colors: ['g', 'w']},
    {name: "Chromium", nickname: "Chromium", colors: ['w', 'u', 'b']},
    {name: "Circu, Dimir Lobotomist", nickname: "Circu", colors: ['u', 'b']},
    {name: "Cloudhoof Kirin", nickname: "Cloudhoof", colors: ['u']},
    {name: "Commander Eesha", nickname: "Eesha", colors: ['w']},
    {name: "Commander Greven il-Vec", nickname: "Greven", colors: ['b']},
    {name: "Cromat", nickname: "Cromat", colors: ['w', 'u', 'b', 'r', 'g']},
    {name: "Crosis, the Purger", nickname: "Crosis", colors: ['u', 'b', 'r']},
    {name: "Crovax, Ascendant Hero", nickname: "Crovax", colors: ['w']},
    {name: "Crovax the Cursed", nickname: "Crovax", colors: ['b']},
    {name: "Daghatar the Adamant", nickname: "Daghatar", colors: ['w', 'b', 'g']},
    {name: "Dakkon Blackblade", nickname: "Dakkon", colors: ['w', 'u', 'b']},
    {name: "Damia, Sage of Stone", nickname: "Damia", colors: ['b', 'g', 'u']},
    {name: "Daretti, Scrap Savant", nickname: "Daretti", colors: ['r']},
    {name: "Darien, King of Kjeldor", nickname: "Darien", colors: ['w']},
    {name: "Darigaaz, the Igniter", nickname: "Darigaaz", colors: ['b', 'r', 'g']},
    {name: "Daughter of Autumn", nickname: "Daughter", colors: ['g', 'w']},
    {name: "Daxos of Meletis", nickname: "Daxos", colors: ['w', 'u']},
    {name: "Daxos the Returned", nickname: "Daxos", colors: ['w', 'b']},
    {name: "Depala, Pilot Exemplar", nickname: "Depala", colors: ['r', 'w']},
    {name: "Derevi, Empyrial Tactician", nickname: "Derevi", colors: ['g', 'w', 'u']},
    {name: "Diaochan, Artful Beauty", nickname: "Diaochan", colors: ['r']},
    {name: "Djeru, With Eyes Open", nickname: "Djeru", colors: ['w']},
    {name: "Dong Zhou, the Tyrant", nickname: "Dong Zhou", colors: ['r']},
    {name: "Doran, the Siege Tower", nickname: "Doran", colors: ['w', 'b', 'g']},
    {name: "Dosan the Falling Leaf", nickname: "Dosan", colors: ['g']},
    {name: "Dragonlord Atarka", nickname: "Atarka", colors: ['r', 'g']},
    {name: "Dragonlord Dromoka", nickname: "Dromoka", colors: ['g', 'w']},
    {name: "Dragonlord Kolaghan", nickname: "Kolaghan", colors: ['b', 'r']},
    {name: "Dragonlord Ojutai", nickname: "Ojutai", colors: ['w', 'u']},
    {name: "Dragonlord Silumgar", nickname: "Silumgar", colors: ['u', 'b']},
    {name: "Dralnu, Lich Lord", nickname: "Dralnu", colors: ['u', 'b']},
    {name: "Drana, Kalastria Bloodchief", nickname: "Drana", colors: ['b']},
    {name: "Drana, Liberator of Malakir", nickname: "Drana", colors: ['b']},
    {name: "Dromar, the Banisher", nickname: "Dromar", colors: ['w', 'u', 'b']},
    {name: "Dromoka, the Eternal", nickname: "Dromoka", colors: ['g', 'w']},
    {name: "Dwynen, Gilt-Leaf Daen", nickname: "Dwynen", colors: ['g']},
    {name: "Edgar Markov", nickname: "Edgar Markov", colors: ['r', 'w', 'b']},
    {name: "Edric, Spymaster of Trest", nickname: "Edric", colors: ['g', 'u']},
    {name: "Eight-and-a-Half-Tails", nickname: "Eight-and-Half", colors: ['w']},
    {name: "Eladamri, Lord of Leaves", nickname: "Eladamri", colors: ['g']},
    {name: "Elesh Norn, Grand Cenobite", nickname: "Elesh Norn", colors: ['w']},
    {name: "Emmara Tandris", nickname: "Emmara Tandris", colors: ['g', 'w']},
    {name: "Empress Galina", nickname: "Empress Galina", colors: ['u']},
    {name: "Emrakul, the Promised End", nickname: "Emrakul", colors: []},
    {name: "Endrek Sahr, Master Breeder", nickname: "Endrek Sahr", colors: ['b']},
    {name: "Ephara, God of the Polis", nickname: "Ephara", colors: ['w', 'u']},
    {name: "Erebos, God of the Dead", nickname: "Erebos", colors: ['b']},
    {name: "Eron the Relentless", nickname: "Eron", colors: ['r']},
    {name: "Ertai, the Corrupted", nickname: "Ertai", colors: ['w', 'u', 'b']},
    {name: "Ertai, Wizard Adept", nickname: "Ertai", colors: ['u']},
    {name: "Exava, Rakdos Blood Witch", nickname: "Exava", colors: ['b', 'r']},
    {name: "Experiment Kraj", nickname: "Kraj", colors: ['g', 'u']},
    {name: "Ezuri, Claw of Progress", nickname: "Ezuri", colors: ['g', 'u']},
    {name: "Ezuri, Renegade Leader", nickname: "Ezuri", colors: ['g']},
    {name: "Feldon of the Third Path", nickname: "Feldon", colors: ['r']},
    {name: "Freyalise, Llanowar's Fury", nickname: "Freyalise", colors: ['g']},
    {name: "Fumiko the Lowblood", nickname: "Fumiko", colors: ['r']},
    {name: "Gabriel Angelfire", nickname: "Gabriel", colors: ['g', 'w']},
    {name: "Gaddock Teeg", nickname: "Gaddock Teeg", colors: ['g', 'w']},
    {name: "Gahiji, Honored One", nickname: "Gahiji", colors: ['r', 'g', 'w']},
    {name: "Gallowbraid", nickname: "Gallowbraid", colors: ['b']},
    {name: "Garza Zol, Plague Queen", nickname: "Garza Zol", colors: ['u', 'b', 'r']},
    {name: "Geist of Saint Traft", nickname: "Geist", colors: ['w', 'u']},
    {name: "General Jarkeld", nickname: "Jarkeld", colors: ['w']},
    {name: "General Tazri", nickname: "General Tazri", colors: ['w', 'u', 'b', 'r', 'g']},
    {name: "Gerrard Capashen", nickname: "Gerrard", colors: ['w']},
    {name: "Geth, Lord of the Vault", nickname: "Geth", colors: ['b']},
    {name: "Ghave, Guru of Spores", nickname: "Ghave", colors: ['w', 'b', 'g']},
    {name: "Ghost Council of Orzhova", nickname: "Ghost Council", colors: ['w', 'b']},
    {name: "Ghoulcaller Gisa", nickname: "Gisa", colors: ['b']},
    {name: "Gisa and Geralf", nickname: "Gisa & Geralf", colors: ['u', 'b']},
    {name: "Gisela, Blade of Goldnight", nickname: "Gisela", colors: ['r', 'w']},
    {name: "Gisela, the Broken Blade", nickname: "Gisela", colors: ['w']},
    {name: "Glissa Sunseeker", nickname: "Glissa", colors: ['g']},
    {name: "Glissa, the Traitor", nickname: "Glissa", colors: ['b', 'g']},
    {name: "Godo, Bandit Warlord", nickname: "Godo", colors: ['r']},
    {name: "Gonti, Lord of Luxury", nickname: "Gonti", colors: ['b']},
    {name: "Gosta Dirk", nickname: "Gosta Dirk", colors: ['w', 'u']},
    {name: "Grand Arbiter Augustin IV", nickname: "Augustin IV", colors: ['w', 'u']},
    {name: "Grandmother Sengir", nickname: "Grandmother", colors: ['b']},
    {name: "Greel, Mind Raker", nickname: "Greel", colors: ['b']},
    {name: "Grenzo, Dungeon Warden", nickname: "Grenzo", colors: ['b', 'r']},
    {name: "Grenzo, Havoc Raiser", nickname: "Grenzo", colors: ['r']},
    {name: "Grimgrin, Corpse-Born", nickname: "Grimgrin", colors: ['u', 'b']},
    {name: "Guan Yu, Sainted Warrior", nickname: "Guan Yu", colors: ['w']},
    {name: "Gwafa Hazid, Profiteer", nickname: "Gwafa Hazid", colors: ['w', 'u']},
    {name: "Gwendlyn Di Corci", nickname: "Gwendlyn", colors: ['u', 'b', 'r']},
    {name: "Haakon, Stromgald Scourge", nickname: "Haakon", colors: ['b']},
    {name: "Hakim, Loreweaver", nickname: "Hakim", colors: ['u']},
    {name: "Halfdane", nickname: "Halfdane", colors: ['w', 'u', 'b']},
    {name: "Hanna, Ship's Navigator", nickname: "Hanna", colors: ['w', 'u']},
    {name: "Hapatra, Vizier of Poisons", nickname: "Hapatra", colors: ['b', 'g']},
    {name: "Hazduhr the Abbot", nickname: "Hazduhr", colors: ['w']},
    {name: "Hazezon Tamar", nickname: "Hazezon Tamar", colors: ['r', 'g', 'w']},
    {name: "Hazoret the Fervent", nickname: "Hazoret", colors: ['r']},
    {name: "Heartless Hidetsugu", nickname: "Hidetsugu", colors: ['r']},
    {name: "Heidar, Rimewind Master", nickname: "Heidar", colors: ['u']},
    {name: "Heliod, God of the Sun", nickname: "Heliod", colors: ['w']},
    {name: "He Who Hungers", nickname: "He Who Hungers", colors: ['b']},
    {name: "Higure, the Still Wind", nickname: "Higure", colors: ['u']},
    {name: "Hikari, Twilight Guardian", nickname: "Hikari", colors: ['w']},
    {name: "Hisoka, Minamo Sensei", nickname: "Hisoka", colors: ['u']},
    {name: "Hivis of the Scale", nickname: "Hivis", colors: ['r']},
    {name: "Hixus, Prison Warden", nickname: "Hixus", colors: ['w']},
    {name: "Hokori, Dust Drinker", nickname: "Hokori", colors: ['w']},
    {name: "Homura, Human Ascendant", nickname: "Homura", colors: ['r']},
    {name: "Hope of Ghirapur", nickname: "Hope", colors: []},
    {name: "Horde of Notions", nickname: "Horde", colors: ['w', 'u', 'b', 'r', 'g']},
    {name: "Horobi, Death's Wail", nickname: "Horobi", colors: ['b']},
    {name: "Huang Zhong, Shu General", nickname: "Huang Zhong", colors: ['w']},
    {name: "Hua Tuo, Honored Physician", nickname: "Hua Tuo", colors: ['g']},
    {name: "Hunding Gjornersen", nickname: "Hunding", colors: ['w', 'u']},
    {name: "Hythonia the Cruel", nickname: "Hythonia", colors: ['b']},
    {name: "Ib Halfheart, Goblin Tactician", nickname: "Ib Halfheart", colors: ['r']},
    {name: "Ihsan's Shade", nickname: "Ihsan's Shade", colors: ['b']},
    {name: "Iizuka the Ruthless", nickname: "Iizuka", colors: ['r']},
    {name: "Ikra Shidiqi, the Usurper", nickname: "Ikra Shidiqi", colors: ['b', 'g']},
    {name: "Inalla, Archmage Ritualist", nickname: "Inalla", colors: ['u', 'b', 'r']},
    {name: "Iname as One", nickname: "Iname as One", colors: ['b', 'g']},
    {name: "Iname, Death Aspect", nickname: "Death Aspect", colors: ['b']},
    {name: "Iname, Life Aspect", nickname: "Life Aspect", colors: ['g']},
    {name: "Infernal Kirin", nickname: "Infernal", colors: ['b']},
    {name: "Ink-Eyes, Servant of Oni", nickname: "Ink-Eyes", colors: ['b']},
    {name: "Intet, the Dreamer", nickname: "Intet", colors: ['g', 'u', 'r']},
    {name: "Iona, Shield of Emeria", nickname: "Iona", colors: ['w']},
    {name: "Irini Sengir", nickname: "Irini Sengir", colors: ['b']},
    {name: "Iroas, God of Victory", nickname: "Iroas", colors: ['r', 'w']},
    {name: "Isamaru, Hound of Konda", nickname: "Isamaru", colors: ['w']},
    {name: "Isao, Enlightened Bushi", nickname: "Isao", colors: ['g']},
    {name: "Ishai, Ojutai Dragonspeaker", nickname: "Ishai", colors: ['w', 'u']},
    {name: "Ishi-Ishi, Akki Crackshot", nickname: "Ishi-Ishi", colors: ['r']},
    {name: "Ishkanah, Grafwidow", nickname: "Ishkanah", colors: ['b', 'g']},
    {name: "Isperia, Supreme Judge", nickname: "Isperia", colors: ['w', 'u']},
    {name: "Isperia the Inscrutable", nickname: "Isperia", colors: ['w', 'u']},
    {name: "Ith, High Arcanist", nickname: "Ith", colors: ['w', 'u']},
    {name: "Iwamori of the Open Fist", nickname: "Iwamori", colors: ['g']},
    {name: "Ixidor, Reality Sculptor", nickname: "Ixidor", colors: ['u']},
    {name: "Jace, Vryn's Prodigy", nickname: "Jace", colors: ['u']},
    {name: "Jacques le Vert", nickname: "Jacques", colors: ['r', 'g', 'w']},
    {name: "Jalira, Master Polymorphist", nickname: "Jalira", colors: ['u']},
    {name: "Jarad, Golgari Lich Lord", nickname: "Jarad", colors: ['b', 'g']},
    {name: "Jareth, Leonine Titan", nickname: "Jareth", colors: ['w']},
    {name: "Jasmine Boreal", nickname: "Jasmine Boreal", colors: ['g', 'w']},
    {name: "Jaya Ballard, Task Mage", nickname: "Jaya Ballard", colors: ['r']},
    {name: "Jazal Goldmane", nickname: "Jazal Goldmane", colors: ['w']},
    {name: "Jedit Ojanen", nickname: "Jedit Ojanen", colors: ['w', 'u']},
    {name: "Jedit Ojanen of Efrava", nickname: "Jedit Ojanen", colors: ['g']},
    {name: "Jeleva, Nephalia's Scourge", nickname: "Jeleva", colors: ['u', 'b', 'r']},
    {name: "Jenara, Asura of War", nickname: "Jenara", colors: ['g', 'w', 'u']},
    {name: "Jerrard of the Closed Fist", nickname: "Jerrard", colors: ['r', 'g']},
    {name: "Jeska, Warrior Adept", nickname: "Jeska", colors: ['r']},
    {name: "Jhoira of the Ghitu", nickname: "Jhoira", colors: ['u', 'r']},
    {name: "Jin-Gitaxias, Core Augur", nickname: "Jin-Gitaxias", colors: ['u']},
    {name: "Jiwari, the Earth Aflame", nickname: "Jiwari", colors: ['r']},
    {name: "Johan", nickname: "Johan", colors: ['r', 'g', 'w']},
    {name: "Jolrael, Empress of Beasts", nickname: "Jolrael", colors: ['g']},
    {name: "Jori En, Ruin Diver", nickname: "Jori En", colors: ['u', 'r']},
    {name: "Jor Kadeen, the Prevailer", nickname: "Jor Kadeen", colors: ['r', 'w']},
    {name: "Joven", nickname: "Joven", colors: ['r']},
    {name: "Jugan, the Rising Star", nickname: "Jugan", colors: ['g']},
    {name: "Kaalia of the Vast", nickname: "Kaalia", colors: ['r', 'w', 'b']},
    {name: "Kaervek the Merciless", nickname: "Kaervek", colors: ['b', 'r']},
    {name: "Kagemaro, First to Suffer", nickname: "Kagemaro", colors: ['b']},
    {name: "Kaho, Minamo Historian", nickname: "Kaho", colors: ['u']},
    {name: "Kalemne, Disciple of Iroas", nickname: "Kalemne", colors: ['r', 'w']},
    {name: "Kalitas, Bloodchief of Ghet", nickname: "Kalitas", colors: ['b']},
    {name: "Kalitas, Traitor of Ghet", nickname: "Kalitas", colors: ['b']},
    {name: "Kamahl, Fist of Krosa", nickname: "Kamahl", colors: ['g']},
    {name: "Kamahl, Pit Fighter", nickname: "Kamahl", colors: ['r']},
    {name: "Kambal, Consul of Allocation", nickname: "Kambal", colors: ['w', 'b']},
    {name: "Kami of the Crescent Moon", nickname: "Kami", colors: ['u']},
    {name: "Kangee, Aerie Keeper", nickname: "Kangee", colors: ['w', 'u']},
    {name: "Karador, Ghost Chieftain", nickname: "Karador", colors: ['w', 'b', 'g']},
    {name: "Karametra, God of Harvests", nickname: "Karametra", colors: ['g', 'w']},
    {name: "Kari Zev, Skyship Raider", nickname: "Kari Zev", colors: ['r']},
    {name: "Karlov of the Ghost Council", nickname: "Karlov", colors: ['w', 'b']},
    {name: "Karn, Silver Golem", nickname: "Karn", colors: []},
    {name: "Karona, False God", nickname: "Karona", colors: ['w', 'u', 'b', 'r', 'g']},
    {name: "Karrthus, Tyrant of Jund", nickname: "Karrthus", colors: ['b', 'r', 'g']},
    {name: "Kaseto, Orochi Archmage", nickname: "Kaseto", colors: ['g', 'u']},
    {name: "Kasimir the Lone Wolf", nickname: "Kasimir", colors: ['w', 'u']},
    {name: "Kataki, War's Wage", nickname: "Kataki", colors: ['w']},
    {name: "Kaysa", nickname: "Kaysa", colors: ['g']},
    {name: "Kazuul, Tyrant of the Cliffs", nickname: "Kazuul", colors: ['r']},
    {name: "Kefnet the Mindful", nickname: "Kefnet", colors: ['u']},
    {name: "Keiga, the Tide Star", nickname: "Keiga", colors: ['u']},
    {name: "Kei Takahashi", nickname: "Kei Takahashi", colors: ['g', 'w']},
    {name: "Kemba, Kha Regent", nickname: "Kemba", colors: ['w']},
    {name: "Kentaro, the Smiling Cat", nickname: "Kentaro", colors: ['w']},
    {name: "Keranos, God of Storms", nickname: "Keranos", colors: ['u', 'r']},
    {name: "Kess, Dissident Mage", nickname: "Kess", colors: ['u', 'b', 'r']},
    {name: "Kiki-Jiki, Mirror Breaker", nickname: "Kiki-Jiki", colors: ['r']},
    {name: "Kiku, Night's Flower", nickname: "Kiku", colors: ['b']},
    {name: "King Macar, the Gold-Cursed", nickname: "King Macar", colors: ['b']},
    {name: "Kira, Great Glass-Spinner", nickname: "Kira", colors: ['u']},
    {name: "Kiyomaro, First to Stand", nickname: "Kiyomaro", colors: ['w']},
    {name: "Kodama of the Center Tree", nickname: "Kodama", colors: ['g']},
    {name: "Kodama of the North Tree", nickname: "Kodama", colors: ['g']},
    {name: "Kodama of the South Tree", nickname: "Kodama", colors: ['g']},
    {name: "Kokusho, the Evening Star", nickname: "Kokusho", colors: ['b']},
    {name: "Kolaghan, the Storm's Fury", nickname: "Kolaghan", colors: ['b', 'r']},
    {name: "Konda, Lord of Eiganjo", nickname: "Konda", colors: ['w']},
    {name: "Kongming, \"Sleeping Dragon\"", nickname: "Kongming", colors: ['w']},
    {name: "Korlash, Heir to Blackblade", nickname: "Korlash", colors: ['b']},
    {name: "Kothophed, Soul Hoarder", nickname: "Kothophed", colors: ['b']},
    {name: "Kozilek, Butcher of Truth", nickname: "Kozilek", colors: []},
    {name: "Kozilek, the Great Distortion", nickname: "Kozilek", colors: []},
    {name: "Kraum, Ludevic's Opus", nickname: "Kraum", colors: ['u', 'r']},
    {name: "Krenko, Mob Boss", nickname: "Krenko", colors: ['r']},
    {name: "Kresh the Bloodbraided", nickname: "Kresh", colors: ['b', 'r', 'g']},
    {name: "Krond the Dawn-Clad", nickname: "Krond", colors: ['g', 'w']},
    {name: "Kruphix, God of Horizons", nickname: "Kruphix", colors: ['g', 'u']},
    {name: "Kumano, Master Yamabushi", nickname: "Kumano", colors: ['r']},
    {name: "Kuon, Ogre Ascendant", nickname: "Kuon", colors: ['b']},
    {name: "Kurkesh, Onakke Ancient", nickname: "Kurkesh", colors: ['r']},
    {name: "Kuro, Pitlord", nickname: "Kuro, Pitlord", colors: ['b']},
    {name: "Kydele, Chosen of Kruphix", nickname: "Kydele", colors: ['g', 'u']},
    {name: "Kynaios and Tiro of Meletis", nickname: "Kynaios & Tiro", colors: ['r', 'g', 'w', 'u']},
    {name: "Kyoki, Sanity's Eclipse", nickname: "Kyoki", colors: ['b']},
    {name: "Kytheon, Hero of Akros", nickname: "Kytheon", colors: ['w']},
    {name: "Lady Caleria", nickname: "Lady Caleria", colors: ['g', 'w']},
    {name: "Lady Evangela", nickname: "Lady Evangela", colors: ['w', 'u', 'b']},
    {name: "Lady Orca", nickname: "Lady Orca", colors: ['b', 'r']},
    {name: "Lady Sun", nickname: "Lady Sun", colors: ['u']},
    {name: "Lady Zhurong, Warrior Queen", nickname: "Lady Zhurong,", colors: ['g']},
    {name: "Latulla, Keldon Overseer", nickname: "Latulla", colors: ['r']},
    {name: "Lavinia of the Tenth", nickname: "Lavinia", colors: ['w', 'u']},
    {name: "Lazav, Dimir Mastermind", nickname: "Lazav", colors: ['u', 'b']},
    {name: "Licia, Sanguine Tribune", nickname: "Licia", colors: ['r', 'w', 'b']},
    {name: "Lieutenant Kirtar", nickname: "Kirtar", colors: ['w']},
    {name: "Liliana, Heretical Healer", nickname: "Liliana", colors: ['b']},
    {name: "Lim-Dul the Necromancer", nickname: "Lim-Dul", colors: ['b']},
    {name: "Linessa, Zephyr Mage", nickname: "Linessa", colors: ['u']},
    {name: "Lin Sivvi, Defiant Hero", nickname: "Lin Sivvi", colors: ['w']},
    {name: "Linvala, Keeper of Silence", nickname: "Linvala", colors: ['w']},
    {name: "Linvala, the Preserver", nickname: "Linvala", colors: ['w']},
    {name: "Liu Bei, Lord of Shu", nickname: "Liu Bei", colors: ['w']},
    {name: "Livonya Silone", nickname: "Livonya Silone", colors: ['r', 'g']},
    {name: "Llawan, Cephalid Empress", nickname: "Llawan", colors: ['u']},
    {name: "Lord Magnus", nickname: "Lord Magnus", colors: ['g', 'w']},
    {name: "Lord of Tresserhorn", nickname: "Tresserhorn", colors: ['u', 'b', 'r']},
    {name: "Lorthos, the Tidemaker", nickname: "Lorthos", colors: ['u']},
    {name: "Lovisa Coldeyes", nickname: "Lovisa", colors: ['r']},
    {name: "Lu Bu, Master-at-Arms", nickname: "Lu Bu", colors: ['r']},
    {name: "Ludevic, Necro-Alchemist", nickname: "Ludevic", colors: ['u', 'r']},
    {name: "Lu Meng, Wu General", nickname: "Lu Meng", colors: ['u']},
    {name: "Lu Su, Wu Advisor", nickname: "Lu Su", colors: ['u']},
    {name: "Lu Xun, Scholar General", nickname: "Lu Xun", colors: ['u']},
    {name: "Lyzolda, the Blood Witch", nickname: "Lyzolda", colors: ['b', 'r']},
    {name: "Ma Chao, Western Warrior", nickname: "Ma Chao", colors: ['r']},
    {name: "Maelstrom Wanderer", nickname: "Wanderer", colors: ['g', 'u', 'r']},
    {name: "Maga, Traitor to Mortals", nickname: "Maga", colors: ['b']},
    {name: "Mageta the Lion", nickname: "Mageta", colors: ['w']},
    {name: "Mairsil, the Pretender", nickname: "Mairsil", colors: ['u', 'b', 'r']},
    {name: "Major Teroh", nickname: "Major Teroh", colors: ['w']},
    {name: "Malfegor", nickname: "Malfegor", colors: ['b', 'r']},
    {name: "Mangara of Corondor", nickname: "Mangara", colors: ['w']},
    {name: "Mannichi, the Fevered Dream", nickname: "Mannichi", colors: ['r']},
    {name: "Maralen of the Mornsong", nickname: "Maralen", colors: ['b']},
    {name: "Marath, Will of the Wild", nickname: "Marath", colors: ['r', 'g', 'w']},
    {name: "Maraxus of Keld", nickname: "Maraxus", colors: ['r']},
    {name: "Marchesa, the Black Rose", nickname: "Marchesa", colors: ['u', 'b', 'r']},
    {name: "Marhault Elsdragon", nickname: "Marhault", colors: ['r', 'g']},
    {name: "Marrow-Gnawer", nickname: "Marrow-Gnawer", colors: ['b']},
    {name: "Marton Stromgald", nickname: "Marton", colors: ['r']},
    {name: "Masako the Humorless", nickname: "Masako", colors: ['w']},
    {name: "Masumaro, First to Live", nickname: "Masumaro", colors: ['g']},
    {name: "Mathas, Fiend Seeker", nickname: "Mathas", colors: ['r', 'w', 'b']},
    {name: "Mayael the Anima", nickname: "Mayael", colors: ['r', 'g', 'w']},
    {name: "Mazirek, Kraul Death Priest", nickname: "Mazirek", colors: ['b', 'g']},
    {name: "Medomai the Ageless", nickname: "Medomai", colors: ['w', 'u']},
    {name: "Melek, Izzet Paragon", nickname: "Melek", colors: ['u', 'r']},
    {name: "Melira, Sylvok Outcast", nickname: "Melira", colors: ['g']},
    {name: "Meloku the Clouded Mirror", nickname: "Meloku", colors: ['u']},
    {name: "Memnarch", nickname: "Memnarch", colors: ['u']},
    {name: "Meng Huo, Barbarian King", nickname: "Meng Huo", colors: ['g']},
    {name: "Meren of Clan Nel Toth", nickname: "Meren", colors: ['b', 'g']},
    {name: "Merieke Ri Berit", nickname: "Merieke", colors: ['w', 'u', 'b']},
    {name: "Michiko Konda, Truth Seeker", nickname: "Michiko Konda", colors: ['w']},
    {name: "Mikaeus, the Lunarch", nickname: "Mikaeus", colors: ['w']},
    {name: "Mikaeus, the Unhallowed", nickname: "Mikaeus", colors: ['b']},
    {name: "Mina and Denn, Wildborn", nickname: "Mina & Denn", colors: ['r', 'g']},
    {name: "Mirko Vosk, Mind Drinker", nickname: "Mirko Vosk", colors: ['u', 'b']},
    {name: "Mirri, Cat Warrior", nickname: "Mirri", colors: ['g']},
    {name: "Mirri the Cursed", nickname: "Mirri", colors: ['b']},
    {name: "Mirri, Weatherlight Duelist", nickname: "Mirri", colors: ['g', 'w']},
    {name: "Mishra, Artificer Prodigy", nickname: "Mishra", colors: ['u', 'b', 'r']},
    {name: "Mistform Ultimus", nickname: "Mistform", colors: ['u']},
    {name: "Mizzix of the Izmagnus", nickname: "Mizzix", colors: ['u', 'r']},
    {name: "Mogis, God of Slaughter", nickname: "Mogis", colors: ['b', 'r']},
    {name: "Molimo, Maro-Sorcerer", nickname: "Molimo", colors: ['g']},
    {name: "Momir Vig, Simic Visionary", nickname: "Momir Vig", colors: ['g', 'u']},
    {name: "Morinfen", nickname: "Morinfen", colors: ['b']},
    {name: "Multani, Maro-Sorcerer", nickname: "Multani", colors: ['g']},
    {name: "Munda, Ambush Leader", nickname: "Munda", colors: ['r', 'w']},
    {name: "Muzzio, Visionary Architect", nickname: "Muzzio", colors: ['u']},
    {name: "Myojin of Cleansing Fire", nickname: "Myojin", colors: ['w']},
    {name: "Myojin of Infinite Rage", nickname: "Myojin", colors: ['r']},
    {name: "Myojin of Life's Web", nickname: "Myojin", colors: ['g']},
    {name: "Myojin of Night's Reach", nickname: "Myojin", colors: ['b']},
    {name: "Myojin of Seeing Winds", nickname: "Myojin", colors: ['u']},
    {name: "Nagao, Bound by Honor", nickname: "Nagao", colors: ['w']},
    {name: "Nahiri, the Lithomancer", nickname: "Nahiri", colors: ['w']},
    {name: "Narset, Enlightened Master", nickname: "Narset", colors: ['u', 'r', 'w']},
    {name: "Nath of the Gilt-Leaf", nickname: "Nath", colors: ['b', 'g']},
    {name: "Nazahn, Revered Bladesmith", nickname: "Nazahn", colors: ['g', 'w']},
    {name: "Nebuchadnezzar", nickname: "Nebuchadnezzar", colors: ['u', 'b']},
    {name: "Nefarox, Overlord of Grixis", nickname: "Nefarox", colors: ['b']},
    {name: "Neheb, the Eternal", nickname: "Neheb", colors: ['r']},
    {name: "Neheb, the Worthy", nickname: "Neheb", colors: ['b', 'r']},
    {name: "Nekusar, the Mindrazer", nickname: "Nekusar", colors: ['u', 'b', 'r']},
    {name: "Nemata, Grove Guardian", nickname: "Nemata", colors: ['g']},
    {name: "Nicol Bolas", nickname: "Nicol Bolas", colors: ['u', 'b', 'r']},
    {name: "Nin, the Pain Artist", nickname: "Nin", colors: ['u', 'r']},
    {name: "Nissa, Vastwood Seer", nickname: "Nissa", colors: ['g']},
    {name: "Niv-Mizzet, Dracogenius", nickname: "Niv-Mizzet", colors: ['u', 'r']},
    {name: "Niv-Mizzet, the Firemind", nickname: "Niv-Mizzet", colors: ['u', 'r']},
    {name: "Norin the Wary", nickname: "Norin the Wary", colors: ['r']},
    {name: "Noyan Dar, Roil Shaper", nickname: "Noyan Dar", colors: ['w', 'u']},
    {name: "Numot, the Devastator", nickname: "Numot", colors: ['u', 'r', 'w']},
    {name: "Nylea, God of the Hunt", nickname: "Nylea", colors: ['g']},
    {name: "Ob Nixilis of the Black Oath", nickname: "Ob Nixilis", colors: ['b']},
    {name: "Ob Nixilis, the Fallen", nickname: "Ob Nixilis", colors: ['b']},
    {name: "Ob Nixilis, Unshackled", nickname: "Ob Nixilis", colors: ['b']},
    {name: "Obzedat, Ghost Council", nickname: "Obzedat", colors: ['w', 'b']},
    {name: "Odric, Lunarch Marshal", nickname: "Odric", colors: ['w']},
    {name: "Odric, Master Tactician", nickname: "Odric", colors: ['w']},
    {name: "Ojutai, Soul of Winter", nickname: "Ojutai", colors: ['w', 'u']},
    {name: "O-Kagachi, Vengeful Kami", nickname: "O-Kagachi", colors: ['w', 'u', 'b', 'r', 'g']},
    {name: "Oketra the True", nickname: "Oketra", colors: ['w']},
    {name: "Olivia, Mobilized for War", nickname: "Olivia", colors: ['b', 'r']},
    {name: "Olivia Voldaren", nickname: "Olivia", colors: ['b', 'r']},
    {name: "Oloro, Ageless Ascetic", nickname: "Oloro", colors: ['w', 'u', 'b']},
    {name: "Omnath, Locus of Mana", nickname: "Omnath", colors: ['g']},
    {name: "Omnath, Locus of Rage", nickname: "Omnath", colors: ['r', 'g']},
    {name: "Oona, Queen of the Fae", nickname: "Oona", colors: ['u', 'b']},
    {name: "Opal-Eye, Konda's Yojimbo", nickname: "Opal-Eye", colors: ['w']},
    {name: "Orim, Samite Healer", nickname: "Orim", colors: ['w']},
    {name: "Oriss, Samite Guardian", nickname: "Oriss", colors: ['w']},
    {name: "Oros, the Avenger", nickname: "Oros", colors: ['r', 'w', 'b']},
    {name: "Oviya Pashiri, Sage Lifecrafter", nickname: "Oviya Pashiri", colors: ['g']},
    {name: "Oyobi, Who Split the Heavens", nickname: "Oyobi", colors: ['w']},
    {name: "Padeem, Consul of Innovation", nickname: "Padeem", colors: ['u']},
    {name: "Palladia-Mors", nickname: "Palladia-Mors", colors: ['r', 'g', 'w']},
    {name: "Pang Tong, \"Young Phoenix\"", nickname: "Pang Tong", colors: ['w']},
    {name: "Patron of the Akki", nickname: "Patron", colors: ['r']},
    {name: "Patron of the Kitsune", nickname: "Patron", colors: ['w']},
    {name: "Patron of the Moon", nickname: "Patron", colors: ['u']},
    {name: "Patron of the Nezumi", nickname: "Patron", colors: ['b']},
    {name: "Patron of the Orochi", nickname: "Patron", colors: ['g']},
    {name: "Pavel Maliki", nickname: "Pavel Maliki", colors: ['b', 'r']},
    {name: "Phage the Untouchable", nickname: "Phage", colors: ['b']},
    {name: "Pharika, God of Affliction", nickname: "Pharika", colors: ['b', 'g']},
    {name: "Phelddagrif", nickname: "Phelddagrif", colors: ['g', 'w', 'u']},
    {name: "Phenax, God of Deception", nickname: "Phenax", colors: ['u', 'b']},
    {name: "Pia and Kiran Nalaar", nickname: "Pia & Kiran", colors: ['r']},
    {name: "Pia Nalaar", nickname: "Pia Nalaar", colors: ['r']},
    {name: "Pianna, Nomad Captain", nickname: "Pianna", colors: ['w']},
    {name: "Polukranos, World Eater", nickname: "Polukranos", colors: ['g']},
    {name: "Prime Speaker Zegana", nickname: "Zegana", colors: ['g', 'u']},
    {name: "Princess Lucrezia", nickname: "Lucrezia", colors: ['u', 'b']},
    {name: "Progenitus", nickname: "Progenitus", colors: ['w', 'u', 'b', 'r', 'g']},
    {name: "Prossh, Skyraider of Kher", nickname: "Prossh", colors: ['b', 'r', 'g']},
    {name: "Purphoros, God of the Forge", nickname: "Purphoros", colors: ['r']},
    {name: "Purraj of Urborg", nickname: "Purraj", colors: ['b']},
    {name: "Queen Marchesa", nickname: "Queen Marchesa", colors: ['r', 'w', 'b']},
    {name: "Radha, Heir to Keld", nickname: "Radha", colors: ['r', 'g']},
    {name: "Radiant, Archangel", nickname: "Radiant", colors: ['w']},
    {name: "Rafiq of the Many", nickname: "Rafiq", colors: ['g', 'w', 'u']},
    {name: "Ragnar", nickname: "Ragnar", colors: ['g', 'w', 'u']},
    {name: "Rakdos, Lord of Riots", nickname: "Rakdos", colors: ['b', 'r']},
    {name: "Rakdos the Defiler", nickname: "Rakdos", colors: ['b', 'r']},
    {name: "Rakka Mar", nickname: "Rakka Mar", colors: ['r']},
    {name: "Raksha Golden Cub", nickname: "Raksha", colors: ['w']},
    {name: "Ramirez DePietro", nickname: "Ramirez", colors: ['u', 'b']},
    {name: "Ramos, Dragon Engine", nickname: "Ramos", colors: ['w', 'u', 'b', 'r', 'g']},
    {name: "Ramses Overdark", nickname: "Ramses", colors: ['u', 'b']},
    {name: "Rashida Scalebane", nickname: "Rashida", colors: ['w']},
    {name: "Rashka the Slayer", nickname: "Rashka", colors: ['w']},
    {name: "Rashmi, Eternities Crafter", nickname: "Rashmi", colors: ['g', 'u']},
    {name: "Rasputin Dreamweaver", nickname: "Rasputin", colors: ['w', 'u']},
    {name: "Ravos, Soultender", nickname: "Ravos", colors: ['w', 'b']},
    {name: "Rayne, Academy Chancellor", nickname: "Rayne", colors: ['u']},
    {name: "Razaketh, the Foulblooded", nickname: "Razaketh", colors: ['b']},
    {name: "Razia, Boros Archangel", nickname: "Razia", colors: ['r', 'w']},
    {name: "Reaper King", nickname: "Reaper King", colors: ['w', 'u', 'b', 'r', 'g']},
    {name: "Reki, the History of Kamigawa", nickname: "Reki", colors: ['g']},
    {name: "Reveka, Wizard Savant", nickname: "Reveka", colors: ['u']},
    {name: "Reya Dawnbringer", nickname: "Reya", colors: ['w']},
    {name: "Reyhan, Last of the Abzan", nickname: "Reyhan", colors: ['b', 'g']},
    {name: "Rhonas the Indomitable", nickname: "Rhonas", colors: ['g']},
    {name: "Rhys the Exiled", nickname: "Rhys", colors: ['b', 'g']},
    {name: "Rhys the Redeemed", nickname: "Rhys", colors: ['g', 'w']},
    {name: "Riku of Two Reflections", nickname: "Riku", colors: ['g', 'u', 'r']},
    {name: "Rishkar, Peema Renegade", nickname: "Rishkar", colors: ['g']},
    {name: "Rith, the Awakener", nickname: "Rith", colors: ['r', 'g', 'w']},
    {name: "Riven Turnbull", nickname: "Riven Turnbull", colors: ['u', 'b']},
    {name: "Rohgahh of Kher Keep", nickname: "Rohgahh", colors: ['b', 'r']},
    {name: "Roon of the Hidden Realm", nickname: "Roon", colors: ['g', 'w', 'u']},
    {name: "Rorix Bladewing", nickname: "Rorix", colors: ['r']},
    {name: "Rosheen Meanderer", nickname: "Rosheen", colors: ['r', 'g']},
    {name: "Rubinia Soulsinger", nickname: "Rubinia", colors: ['g', 'w', 'u']},
    {name: "Ruhan of the Fomori", nickname: "Ruhan", colors: ['u', 'r', 'w']},
    {name: "Rune-Tail, Kitsune Ascendant", nickname: "Rune-Tail", colors: ['w']},
    {name: "Ruric Thar, the Unbowed", nickname: "Ruric Thar", colors: ['r', 'g']},
    {name: "Ryusei, the Falling Star", nickname: "Ryusei", colors: ['r']},
    {name: "Sachi, Daughter of Seshiro", nickname: "Sachi", colors: ['g']},
    {name: "Saffi Eriksdotter", nickname: "Saffi", colors: ['g', 'w']},
    {name: "Sakashima the Impostor", nickname: "Sakashima", colors: ['u']},
    {name: "Sakiko, Mother of Summer", nickname: "Sakiko", colors: ['g']},
    {name: "Samut, Voice of Dissent", nickname: "Samut", colors: ['r', 'g', 'w']},
    {name: "Sapling of Colfenor", nickname: "Sapling", colors: ['b', 'g']},
    {name: "Sasaya, Orochi Ascendant", nickname: "Sasaya", colors: ['g']},
    {name: "Saskia the Unyielding", nickname: "Saskia", colors: ['b', 'r', 'g', 'w']},
    {name: "Savra, Queen of the Golgari", nickname: "Savra", colors: ['b', 'g']},
    {name: "Scion of the Ur-Dragon", nickname: "Scion", colors: ['w', 'u', 'b', 'r', 'g']},
    {name: "Sedris, the Traitor King", nickname: "Sedris", colors: ['u', 'b', 'r']},
    {name: "Seizan, Perverter of Truth", nickname: "Seizan", colors: ['b']},
    {name: "Sekki, Seasons' Guide", nickname: "Sekki", colors: ['g']},
    {name: "Sek'Kuar, Deathkeeper", nickname: "Sek'Kuar", colors: ['b', 'r', 'g']},
    {name: "Selenia, Dark Angel", nickname: "Selenia", colors: ['w', 'b']},
    {name: "Selvala, Explorer Returned", nickname: "Selvala", colors: ['g', 'w']},
    {name: "Selvala, Heart of the Wilds", nickname: "Selvala", colors: ['g']},
    {name: "Sensei Golden-Tail", nickname: "Golden-Tail", colors: ['w']},
    {name: "Sen Triplets", nickname: "Sen Triplets", colors: ['w', 'u', 'b']},
    {name: "Seshiro the Anointed", nickname: "Seshiro", colors: ['g']},
    {name: "Seton, Krosan Protector", nickname: "Seton", colors: ['g']},
    {name: "Sharuum the Hegemon", nickname: "Sharuum", colors: ['w', 'u', 'b']},
    {name: "Shattergang Brothers", nickname: "Shattergang", colors: ['b', 'r', 'g']},
    {name: "Shauku, Endbringer", nickname: "Shauku", colors: ['b']},
    {name: "Sheoldred, Whispering One", nickname: "Sheoldred", colors: ['b']},
    {name: "Shimatsu the Bloodcloaked", nickname: "Shimatsu", colors: ['r']},
    {name: "Shirei, Shizo's Caretaker", nickname: "Shirei", colors: ['b']},
    {name: "Shisato, Whispering Hunter", nickname: "Shisato", colors: ['g']},
    {name: "Shizuko, Caller of Autumn", nickname: "Shizuko", colors: ['g']},
    {name: "Shu Yun, the Silent Tempest", nickname: "Shu Yun", colors: ['u', 'r', 'w']},
    {name: "Sidar Jabari", nickname: "Sidar Jabari", colors: ['w']},
    {name: "Sidar Kondo of Jamuraa", nickname: "Sidar Kondo", colors: ['g', 'w']},
    {name: "Sidisi, Brood Tyrant", nickname: "Sidisi", colors: ['b', 'g', 'u']},
    {name: "Sidisi, Undead Vizier", nickname: "Sidisi", colors: ['b']},
    {name: "Sigarda, Heron's Grace", nickname: "Sigarda", colors: ['g', 'w']},
    {name: "Sigarda, Host of Herons", nickname: "Sigarda", colors: ['g', 'w']},
    {name: "Silas Renn, Seeker Adept", nickname: "Silas Renn", colors: ['u', 'b']},
    {name: "Silumgar, the Drifting Death", nickname: "Silumgar", colors: ['u', 'b']},
    {name: "Silvos, Rogue Elemental", nickname: "Silvos", colors: ['g']},
    {name: "Sima Yi, Wei Field Marshal", nickname: "Sima Yi", colors: ['b']},
    {name: "Sir Shandlar of Eberyn", nickname: "Sir Shandlar", colors: ['g', 'w']},
    {name: "Sisters of Stone Death", nickname: "Sisters", colors: ['b', 'g']},
    {name: "Sivitri Scarzam", nickname: "Sivitri", colors: ['u', 'b']},
    {name: "Skeleton Ship", nickname: "Skeleton Ship", colors: ['u', 'b']},
    {name: "Skithiryx, the Blight Dragon", nickname: "Skithiryx", colors: ['b']},
    {name: "Skullbriar, the Walking Grave", nickname: "Skullbriar", colors: ['b', 'g']},
    {name: "Skyfire Kirin", nickname: "Skyfire Kirin", colors: ['r']},
    {name: "Sliver Hivelord", nickname: "Hivelord", colors: ['w', 'u', 'b', 'r', 'g']},
    {name: "Sliver Legion", nickname: "Sliver Legion", colors: ['w', 'u', 'b', 'r', 'g']},
    {name: "Sliver Overlord", nickname: "Overlord", colors: ['w', 'u', 'b', 'r', 'g']},
    {name: "Sliver Queen", nickname: "Sliver Queen", colors: ['w', 'u', 'b', 'r', 'g']},
    {name: "Slobad, Goblin Tinkerer", nickname: "Slobad", colors: ['r']},
    {name: "Sol'kanar the Swamp King", nickname: "Sol'kanar", colors: ['u', 'b', 'r']},
    {name: "Soramaro, First to Dream", nickname: "Soramaro", colors: ['u']},
    {name: "Soraya the Falconer", nickname: "Soraya", colors: ['w']},
    {name: "Sosuke, Son of Seshiro", nickname: "Sosuke", colors: ['g']},
    {name: "Spirit of the Night", nickname: "Spirit", colors: ['b']},
    {name: "Squee, Goblin Nabob", nickname: "Squee", colors: ['r']},
    {name: "Sram, Senior Edificer", nickname: "Sram", colors: ['w']},
    {name: "Stangg", nickname: "Stangg", colors: ['r', 'g']},
    {name: "Starke of Rath", nickname: "Starke of Rath", colors: ['r']},
    {name: "Stitcher Geralf", nickname: "Geralf", colors: ['u']},
    {name: "Stonebrow, Krosan Hero", nickname: "Stonebrow", colors: ['r', 'g']},
    {name: "Sunastian Falconer", nickname: "Sunastian", colors: ['r', 'g']},
    {name: "Sun Ce, Young Conquerer", nickname: "Sun Ce", colors: ['u']},
    {name: "Sun Quan, Lord of Wu", nickname: "Sun Quan", colors: ['u']},
    {name: "Surrak Dragonclaw", nickname: "Surrak", colors: ['g', 'u', 'r']},
    {name: "Surrak, the Hunt Caller", nickname: "Surrak", colors: ['g']},
    {name: "Sydri, Galvanic Genius", nickname: "Sydri", colors: ['w', 'u', 'b']},
    {name: "Sygg, River Cutthroat", nickname: "Sygg", colors: ['u', 'b']},
    {name: "Sygg, River Guide", nickname: "Sygg", colors: ['w', 'u']},
    {name: "Szadek, Lord of Secrets", nickname: "Szadek", colors: ['u', 'b']},
    {name: "Tahngarth, Talruum Hero", nickname: "Tahngarth", colors: ['r']},
    {name: "Taigam, Ojutai Master", nickname: "Taigam", colors: ['w', 'u']},
    {name: "Taigam, Sidisi's Hand", nickname: "Taigam", colors: ['u', 'b']},
    {name: "Tajic, Blade of the Legion", nickname: "Tajic", colors: ['r', 'w']},
    {name: "Takeno, Samurai General", nickname: "Takeno", colors: ['w']},
    {name: "Talrand, Sky Summoner", nickname: "Talrand", colors: ['u']},
    {name: "Tana, the Bloodsower", nickname: "Tana", colors: ['r', 'g']},
    {name: "Taniwha", nickname: "Taniwha", colors: ['u']},
    {name: "Tariel, Reckoner of Souls", nickname: "Tariel", colors: ['r', 'w', 'b']},
    {name: "Tarox Bladewing", nickname: "Tarox", colors: ['r']},
    {name: "Tasigur, the Golden Fang", nickname: "Tasigur", colors: ['b', 'g', 'u']},
    {name: "Teferi, Mage of Zhalfir", nickname: "Teferi", colors: ['u']},
    {name: "Teferi, Temporal Archmage", nickname: "Teferi", colors: ['u']},
    {name: "Telim'Tor", nickname: "Telim'Tor", colors: ['r']},
    {name: "Temmet, Vizier of Naktamun", nickname: "Temmet", colors: ['w', 'u']},
    {name: "Teneb, the Harvester", nickname: "Teneb", colors: ['w', 'b', 'g']},
    {name: "Tetsuo Umezawa", nickname: "Tetsuo Umezawa", colors: ['u', 'b', 'r']},
    {name: "Teysa, Envoy of Ghosts", nickname: "Teysa", colors: ['w', 'b']},
    {name: "Teysa, Orzhov Scion", nickname: "Teysa", colors: ['w', 'b']},
    {name: "Thada Adel, Acquisitor", nickname: "Thada Adel", colors: ['u']},
    {name: "Thalia, Guardian of Thraben", nickname: "Thalia", colors: ['w']},
    {name: "Thalia, Heretic Cathar", nickname: "Thalia", colors: ['w']},
    {name: "Thassa, God of the Sea", nickname: "Thassa", colors: ['u']},
    {name: "The Gitrog Monster", nickname: "Gitrog Monster", colors: ['b', 'g']},
    {name: "The Lady of the Mountain", nickname: "The Lady", colors: ['r', 'g']},
    {name: "The Locust God", nickname: "Locust God", colors: ['u', 'r']},
    {name: "Thelon of Havenwood", nickname: "Thelon", colors: ['b', 'g']},
    {name: "The Mimeoplasm", nickname: "The Mimeoplasm", colors: ['b', 'g', 'u']},
    {name: "The Scarab God", nickname: "Scarab God", colors: ['u', 'b']},
    {name: "The Scorpion God", nickname: "Scorpion God", colors: ['b', 'r']},
    {name: "The Unspeakable", nickname: "Unspeakable", colors: ['u']},
    {name: "The Ur-Dragon", nickname: "Ur-Dragon", colors: ['w', 'u', 'b', 'r', 'g']},
    {name: "Thrasios, Triton Hero", nickname: "Thrasios", colors: ['g', 'u']},
    {name: "Thraximundar", nickname: "Thraximundar", colors: ['u', 'b', 'r']},
    {name: "Thriss, Nantuko Primus", nickname: "Thriss", colors: ['g']},
    {name: "Thromok the Insatiable", nickname: "Thromok", colors: ['r', 'g']},
    {name: "Thrun, the Last Troll", nickname: "Thrun", colors: ['g']},
    {name: "Tibor and Lumia", nickname: "Tibor & Lumia", colors: ['u', 'r']},
    {name: "Titania, Protector of Argoth", nickname: "Titania", colors: ['g']},
    {name: "Tivadar of Thorn", nickname: "Tivadar", colors: ['w']},
    {name: "Tobias Andrion", nickname: "Tobias Andrion", colors: ['w', 'u']},
    {name: "Tolsimir Wolfblood", nickname: "Tolsimir", colors: ['g', 'w']},
    {name: "Tomorrow, Azami's Familiar", nickname: "Tomorrow", colors: ['u']},
    {name: "Torsten Von Ursus", nickname: "Torsten", colors: ['g', 'w']},
    {name: "Tor Wauki", nickname: "Tor Wauki", colors: ['b', 'r']},
    {name: "Toshiro Umezawa", nickname: "Toshiro", colors: ['b']},
    {name: "Treva, the Renewer", nickname: "Treva", colors: ['g', 'w', 'u']},
    {name: "Triad of Fates", nickname: "Triad of Fates", colors: ['w', 'b']},
    {name: "Tromokratis", nickname: "Tromokratis", colors: ['u']},
    {name: "Trostani, Selesnya's Voice", nickname: "Trostani", colors: ['g', 'w']},
    {name: "Tsabo Tavoc", nickname: "Tsabo Tavoc", colors: ['b', 'r']},
    {name: "Tuknir Deathlock", nickname: "Tuknir", colors: ['r', 'g']},
    {name: "Tuktuk the Explorer", nickname: "Tuktuk", colors: ['r']},
    {name: "Tymaret, the Murder King", nickname: "Tymaret", colors: ['b', 'r']},
    {name: "Tymna the Weaver", nickname: "Tymna", colors: ['w', 'b']},
    {name: "Ulamog, the Ceaseless Hunger", nickname: "Ulamog", colors: []},
    {name: "Ulamog, the Infinite Gyre", nickname: "Ulamog", colors: []},
    {name: "Ulasht, the Hate Seed", nickname: "Ulasht", colors: ['r', 'g']},
    {name: "Ulrich of the Krallenhorde", nickname: "Ulrich", colors: ['r', 'g']},
    {name: "Unesh, Criosphinx Sovereign", nickname: "Unesh", colors: ['u']},
    {name: "Urabrask the Hidden", nickname: "Urabrask", colors: ['r']},
    {name: "Ur-Drago", nickname: "Ur-Drago", colors: ['u', 'b']},
    {name: "Uril, the Miststalker", nickname: "Uril", colors: ['r', 'g', 'w']},
    {name: "Uyo, Silent Prophet", nickname: "Uyo", colors: ['u']},
    {name: "Vaevictis Asmadi", nickname: "Vaevictis", colors: ['b', 'r', 'g']},
    {name: "Varolz, the Scar-Striped", nickname: "Varolz", colors: ['b', 'g']},
    {name: "Vela the Night-Clad", nickname: "Vela", colors: ['u', 'b']},
    {name: "Veldrane of Sengir", nickname: "Veldrane", colors: ['b']},
    {name: "Vendilion Clique", nickname: "Vendilion", colors: ['u']},
    {name: "Venser, Shaper Savant", nickname: "Venser", colors: ['u']},
    {name: "Verdeloth the Ancient", nickname: "Verdeloth", colors: ['g']},
    {name: "Vhati il-Dal", nickname: "Vhati il-Dal", colors: ['b', 'g']},
    {name: "Vial Smasher the Fierce", nickname: "Vial Smasher", colors: ['b', 'r']},
    {name: "Visara the Dreadful", nickname: "Visara", colors: ['b']},
    {name: "Vish Kal, Blood Arbiter", nickname: "Vish Kal", colors: ['w', 'b']},
    {name: "Volrath the Fallen", nickname: "Volrath", colors: ['b']},
    {name: "Vorel of the Hull Clade", nickname: "Vorel", colors: ['g', 'u']},
    {name: "Vorinclex, Voice of Hunger", nickname: "Vorinclex", colors: ['g']},
    {name: "Vorosh, the Hunter", nickname: "Vorosh", colors: ['b', 'g', 'u']},
    {name: "Wasitora, Nekoru Queen", nickname: "Wasitora", colors: ['b', 'r', 'g']},
    {name: "Wort, Boggart Auntie", nickname: "Wort", colors: ['b', 'r']},
    {name: "Wort, the Raidmother", nickname: "Wort", colors: ['r', 'g']},
    {name: "Wrexial, the Risen Deep", nickname: "Wrexial", colors: ['u', 'b']},
    {name: "Wydwen, the Biting Gale", nickname: "Wydwen", colors: ['u', 'b']},
    {name: "Xenagos, God of Revels", nickname: "Xenagos", colors: ['r', 'g']},
    {name: "Xiahou Dun, the One-Eyed", nickname: "Xiahou Dun", colors: ['b']},
    {name: "Xira Arien", nickname: "Xira Arien", colors: ['b', 'r', 'g']},
    {name: "Xun Yu, Wei Advisor", nickname: "Xun Yu", colors: ['b']},
    {name: "Yahenni, Undying Partisan", nickname: "Yahenni", colors: ['b']},
    {name: "Yasova Dragonclaw", nickname: "Yasova", colors: ['g', 'u', 'r']},
    {name: "Yeva, Nature's Herald", nickname: "Yeva", colors: ['g']},
    {name: "Yidris, Maelstrom Wielder", nickname: "Yidris", colors: ['u', 'b', 'r', 'g']},
    {name: "Yisan, the Wanderer Bard", nickname: "Yisan", colors: ['g']},
    {name: "Yomiji, Who Bars the Way", nickname: "Yomiji", colors: ['w']},
    {name: "Yosei, the Morning Star", nickname: "Yosei", colors: ['w']},
    {name: "Yuan Shao, the Indecisive", nickname: "Yuan Shao", colors: ['r']},
    {name: "Yukora, the Prisoner", nickname: "Yukora", colors: ['b']},
    {name: "Zada, Hedron Grinder", nickname: "Zada", colors: ['r']},
    {name: "Zedruu the Greathearted", nickname: "Zedruu", colors: ['u', 'r', 'w']},
    {name: "Zhang Fei, Fierce Warrior", nickname: "Zhang Fei", colors: ['w']},
    {name: "Zhang He, Wei General", nickname: "Zhang He", colors: ['b']},
    {name: "Zhang Liao, Hero of Hefei", nickname: "Zhang Liao", colors: ['b']},
    {name: "Zhao Zilong, Tiger General", nickname: "Zhao Zilong", colors: ['w']},
    {name: "Zhou Yu, Chief Commander", nickname: "Zhou Yu", colors: ['u']},
    {name: "Zhuge Jin, Wu Strategist", nickname: "Zhuge Jin", colors: ['u']},
    {name: "Zirilan of the Claw", nickname: "Zirilan", colors: ['r']},
    {name: "Zo-Zu the Punisher", nickname: "Zo-Zu", colors: ['r']},
    {name: "Zuberi, Golden Feather", nickname: "Zuberi", colors: ['w']},
    {name: "Zuo Ci, the Mocking Sage", nickname: "Zuo Ci", colors: ['g']},
    {name: "Zurgo Bellstriker", nickname: "Zurgo", colors: ['r']},
    {name: "Zurgo Helmsmasher", nickname: "Zurgo", colors: ['r', 'w', 'b']},
    {name: "Zur the Enchanter", nickname: "Zur", colors: ['w', 'u', 'b']}
  ],
  datalist: {
    primary: [],
    secondary: []
  }
}

const mutations = {
  /*
  * Filters the datalist of commanders base on input
  */
  filterDatalist (state, args) {
    const commandersList = args.commandersList
    const value = args.commanderName
    // const value = state.args.commanders[args.id].name
    const regex = new RegExp(value, 'i')

    if (value.length > 2) {
      state.datalist[args.id] = commandersList.filter(commander => 
        commander.name.search(regex) > -1
      )

      // Remove list of exact match
      if (state.datalist[args.id].length === 1) {
        if (state.datalist[args.id][0].name === value) {
          state.datalist[args.id] = []
        }
      }
    }
  }
}

export default {
  namespaced,
  state,
  mutations
}